/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gtkpod (void)
{
  GtkWidget *gtkpod;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *menuitem10;
  GtkWidget *menuitem10_menu;
  GtkWidget *import_itunes_mi;
  GtkWidget *image311;
  GtkWidget *add_files1;
  GtkWidget *image312;
  GtkWidget *add_directory1;
  GtkWidget *image313;
  GtkWidget *add_playlist1;
  GtkWidget *image314;
  GtkWidget *export_itunes1;
  GtkWidget *image315;
  GtkWidget *export_files_to_disk1;
  GtkWidget *image316;
  GtkWidget *separatormenuitem1;
  GtkWidget *offline_menu;
  GtkWidget *trennlinie1;
  GtkWidget *ipod_directories;
  GtkWidget *image317;
  GtkWidget *trennlinie3;
  GtkWidget *quit1;
  GtkWidget *menuitem11;
  GtkWidget *menuitem11_menu;
  GtkWidget *new_playlist1;
  GtkWidget *image318;
  GtkWidget *separator1;
  GtkWidget *update_song_info_from_file1;
  GtkWidget *image319;
  GtkWidget *update_song_info_from_file1_menu;
  GtkWidget *songs_in_selected_playlist1;
  GtkWidget *songs_in_selected_tab_entry1;
  GtkWidget *songs_in_selected_tab_entry1_menu;
  GtkWidget *tab_entry_1;
  GtkWidget *tab_entry_2;
  GtkWidget *selected_songs1;
  GtkWidget *separator3;
  GtkWidget *delete_playlist1;
  GtkWidget *image320;
  GtkWidget *delete_selected_tab_entry1;
  GtkWidget *image321;
  GtkWidget *delete_selected_tab_entry1_menu;
  GtkWidget *sort_tab_2;
  GtkWidget *sort_tab_3;
  GtkWidget *delete_song;
  GtkWidget *image322;
  GtkWidget *separator2;
  GtkWidget *edit_preferences1;
  GtkWidget *image323;
  GtkWidget *item1;
  GtkWidget *item1_menu;
  GtkWidget *sort_tab_0;
  GtkWidget *sort_tab_0_menu;
  GtkWidget *alphabetize0_up;
  GtkWidget *image324;
  GtkWidget *alphabetize0_down;
  GtkWidget *image325;
  GtkWidget *re_init0;
  GtkWidget *image326;
  GtkWidget *sort_tab_1;
  GtkWidget *sort_tab_1_menu;
  GtkWidget *alphabetize1_up;
  GtkWidget *image327;
  GtkWidget *alphabetize1_down;
  GtkWidget *image328;
  GtkWidget *re_init1;
  GtkWidget *image329;
  GtkWidget *menuitem13;
  GtkWidget *menuitem13_menu;
  GtkWidget *about1;
  GtkWidget *image330;
  GtkWidget *toolbar;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *import_button;
  GtkWidget *add_files_button;
  GtkWidget *add_dirs_button;
  GtkWidget *add_PL_button;
  GtkWidget *new_PL_button;
  GtkWidget *export_button;
  GtkWidget *stop_button;
  GtkWidget *paned0;
  GtkWidget *scrolledwindow8;
  GtkWidget *playlist_treeview;
  GtkWidget *paned2;
  GtkWidget *paned1;
  GtkWidget *sorttab0;
  GtkWidget *scrolledwindow9;
  GtkWidget *st0_cat0_treeview;
  GtkWidget *label8;
  GtkWidget *scrolledwindow12;
  GtkWidget *st0_cat1_treeview;
  GtkWidget *label9;
  GtkWidget *scrolledwindow13;
  GtkWidget *st0_cat2_treeview;
  GtkWidget *label10;
  GtkWidget *scrolledwindow16;
  GtkWidget *st0_cat3_treeview;
  GtkWidget *label14;
  GtkWidget *scrolledwindow18;
  GtkWidget *st0_cat4_treeview;
  GtkWidget *label23;
  GtkWidget *sorttab1;
  GtkWidget *scrolledwindow15;
  GtkWidget *st1_cat0_treeview;
  GtkWidget *label11;
  GtkWidget *scrolledwindow14;
  GtkWidget *st1_cat1_treeview;
  GtkWidget *label12;
  GtkWidget *scrolledwindow10;
  GtkWidget *st1_cat2_treeview;
  GtkWidget *label13;
  GtkWidget *scrolledwindow17;
  GtkWidget *st1_cat3_treeview;
  GtkWidget *label15;
  GtkWidget *scrolledwindow19;
  GtkWidget *st1_cat4_treeview;
  GtkWidget *label24;
  GtkWidget *scrolledwindow11;
  GtkWidget *song_treeview;
  GtkWidget *hbox5;
  GtkWidget *gtkpod_status;
  GtkWidget *songs_statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  gtkpod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gtkpod), _("gtkpod"));
  gtk_window_set_default_size (GTK_WINDOW (gtkpod), 600, 500);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (gtkpod), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);

  menuitem10 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem10);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem10);

  menuitem10_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem10), menuitem10_menu);

  import_itunes_mi = gtk_image_menu_item_new_with_mnemonic (_("_Import iTunes"));
  gtk_widget_show (import_itunes_mi);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), import_itunes_mi);

  image311 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image311);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (import_itunes_mi), image311);

  add_files1 = gtk_image_menu_item_new_with_mnemonic (_("Add _Files"));
  gtk_widget_show (add_files1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_files1);

  image312 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image312);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_files1), image312);

  add_directory1 = gtk_image_menu_item_new_with_mnemonic (_("Add _Directory"));
  gtk_widget_show (add_directory1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_directory1);

  image313 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image313);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_directory1), image313);

  add_playlist1 = gtk_image_menu_item_new_with_mnemonic (_("Add _Playlist"));
  gtk_widget_show (add_playlist1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_playlist1);

  image314 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image314);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_playlist1), image314);

  export_itunes1 = gtk_image_menu_item_new_with_mnemonic (_("_Export iTunes"));
  gtk_widget_show (export_itunes1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), export_itunes1);

  image315 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image315);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (export_itunes1), image315);

  export_files_to_disk1 = gtk_image_menu_item_new_with_mnemonic (_("Export Files _to Disk"));
  gtk_widget_show (export_files_to_disk1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), export_files_to_disk1);

  image316 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image316);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (export_files_to_disk1), image316);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  offline_menu = gtk_check_menu_item_new_with_mnemonic (_("_Offline"));
  gtk_widget_show (offline_menu);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), offline_menu);

  trennlinie1 = gtk_menu_item_new ();
  gtk_widget_show (trennlinie1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), trennlinie1);
  gtk_widget_set_sensitive (trennlinie1, FALSE);

  ipod_directories = gtk_image_menu_item_new_with_mnemonic (_("_Create iPod's Directories"));
  gtk_widget_show (ipod_directories);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), ipod_directories);

  image317 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image317);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ipod_directories), image317);

  trennlinie3 = gtk_menu_item_new ();
  gtk_widget_show (trennlinie3);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), trennlinie3);
  gtk_widget_set_sensitive (trennlinie3, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), quit1);

  menuitem11 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem11);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem11);

  menuitem11_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem11), menuitem11_menu);

  new_playlist1 = gtk_image_menu_item_new_with_mnemonic (_("_New Playlist"));
  gtk_widget_show (new_playlist1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), new_playlist1);

  image318 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image318);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_playlist1), image318);

  separator1 = gtk_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  update_song_info_from_file1 = gtk_image_menu_item_new_with_mnemonic (_("_Update Song Info from File"));
  gtk_widget_show (update_song_info_from_file1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), update_song_info_from_file1);

  image319 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image319);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (update_song_info_from_file1), image319);

  update_song_info_from_file1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (update_song_info_from_file1), update_song_info_from_file1_menu);

  songs_in_selected_playlist1 = gtk_menu_item_new_with_mnemonic (_("Songs in Selected _Playlist"));
  gtk_widget_show (songs_in_selected_playlist1);
  gtk_container_add (GTK_CONTAINER (update_song_info_from_file1_menu), songs_in_selected_playlist1);

  songs_in_selected_tab_entry1 = gtk_menu_item_new_with_mnemonic (_("Songs in Selected _Tab Entry"));
  gtk_widget_show (songs_in_selected_tab_entry1);
  gtk_container_add (GTK_CONTAINER (update_song_info_from_file1_menu), songs_in_selected_tab_entry1);

  songs_in_selected_tab_entry1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (songs_in_selected_tab_entry1), songs_in_selected_tab_entry1_menu);

  tab_entry_1 = gtk_menu_item_new_with_mnemonic (_("Sort Tab _1"));
  gtk_widget_show (tab_entry_1);
  gtk_container_add (GTK_CONTAINER (songs_in_selected_tab_entry1_menu), tab_entry_1);

  tab_entry_2 = gtk_menu_item_new_with_mnemonic (_("Sort Tab _2"));
  gtk_widget_show (tab_entry_2);
  gtk_container_add (GTK_CONTAINER (songs_in_selected_tab_entry1_menu), tab_entry_2);

  selected_songs1 = gtk_menu_item_new_with_mnemonic (_("Selected _Songs"));
  gtk_widget_show (selected_songs1);
  gtk_container_add (GTK_CONTAINER (update_song_info_from_file1_menu), selected_songs1);

  separator3 = gtk_menu_item_new ();
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  delete_playlist1 = gtk_image_menu_item_new_with_mnemonic (_("Delete Selected _Playlist"));
  gtk_widget_show (delete_playlist1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), delete_playlist1);

  image320 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image320);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (delete_playlist1), image320);

  delete_selected_tab_entry1 = gtk_image_menu_item_new_with_mnemonic (_("Delete Selected _Tab Entry"));
  gtk_widget_show (delete_selected_tab_entry1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), delete_selected_tab_entry1);

  image321 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image321);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (delete_selected_tab_entry1), image321);

  delete_selected_tab_entry1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (delete_selected_tab_entry1), delete_selected_tab_entry1_menu);

  sort_tab_2 = gtk_menu_item_new_with_mnemonic (_("Sort Tab _1"));
  gtk_widget_show (sort_tab_2);
  gtk_container_add (GTK_CONTAINER (delete_selected_tab_entry1_menu), sort_tab_2);

  sort_tab_3 = gtk_menu_item_new_with_mnemonic (_("Sort Tab _2"));
  gtk_widget_show (sort_tab_3);
  gtk_container_add (GTK_CONTAINER (delete_selected_tab_entry1_menu), sort_tab_3);

  delete_song = gtk_image_menu_item_new_with_mnemonic (_("Delete Selected _Songs"));
  gtk_widget_show (delete_song);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), delete_song);

  image322 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image322);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (delete_song), image322);

  separator2 = gtk_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  edit_preferences1 = gtk_image_menu_item_new_with_mnemonic (_("_Edit Preferences"));
  gtk_widget_show (edit_preferences1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), edit_preferences1);
  gtk_widget_add_accelerator (edit_preferences1, "activate", accel_group,
                              GDK_p, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image323 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image323);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_preferences1), image323);

  item1 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (item1);
  gtk_container_add (GTK_CONTAINER (menubar), item1);

  item1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (item1), item1_menu);

  sort_tab_0 = gtk_menu_item_new_with_mnemonic (_("Sort Tab _1"));
  gtk_widget_show (sort_tab_0);
  gtk_container_add (GTK_CONTAINER (item1_menu), sort_tab_0);

  sort_tab_0_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (sort_tab_0), sort_tab_0_menu);

  alphabetize0_up = gtk_image_menu_item_new_with_mnemonic (_("_Alphabetize"));
  gtk_widget_show (alphabetize0_up);
  gtk_container_add (GTK_CONTAINER (sort_tab_0_menu), alphabetize0_up);

  image324 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image324);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (alphabetize0_up), image324);

  alphabetize0_down = gtk_image_menu_item_new_with_mnemonic (_("Alphabeti_ze"));
  gtk_widget_show (alphabetize0_down);
  gtk_container_add (GTK_CONTAINER (sort_tab_0_menu), alphabetize0_down);

  image325 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image325);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (alphabetize0_down), image325);

  re_init0 = gtk_image_menu_item_new_with_mnemonic (_("_Re-init"));
  gtk_widget_show (re_init0);
  gtk_container_add (GTK_CONTAINER (sort_tab_0_menu), re_init0);

  image326 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image326);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (re_init0), image326);

  sort_tab_1 = gtk_menu_item_new_with_mnemonic (_("Sort Tab _2"));
  gtk_widget_show (sort_tab_1);
  gtk_container_add (GTK_CONTAINER (item1_menu), sort_tab_1);

  sort_tab_1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (sort_tab_1), sort_tab_1_menu);

  alphabetize1_up = gtk_image_menu_item_new_with_mnemonic (_("_Alphabetize"));
  gtk_widget_show (alphabetize1_up);
  gtk_container_add (GTK_CONTAINER (sort_tab_1_menu), alphabetize1_up);

  image327 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image327);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (alphabetize1_up), image327);

  alphabetize1_down = gtk_image_menu_item_new_with_mnemonic (_("Alphabeti_ze"));
  gtk_widget_show (alphabetize1_down);
  gtk_container_add (GTK_CONTAINER (sort_tab_1_menu), alphabetize1_down);

  image328 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image328);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (alphabetize1_down), image328);

  re_init1 = gtk_image_menu_item_new_with_mnemonic (_("_Re-init"));
  gtk_widget_show (re_init1);
  gtk_container_add (GTK_CONTAINER (sort_tab_1_menu), re_init1);

  image329 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image329);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (re_init1), image329);

  menuitem13 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem13);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem13);

  menuitem13_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem13), menuitem13_menu);

  about1 = gtk_image_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem13_menu), about1);

  image330 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image330);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image330);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-goto-top", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  import_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Import"),
                                _("Read Existing Database from Disk/iPod"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (import_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  add_files_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Files"),
                                _("Add Files or Directories"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (add_files_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  add_dirs_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Dirs"),
                                _("Add Directories Recursively"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (add_dirs_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  add_PL_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Playlist"),
                                _("Add playlist from file"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (add_PL_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-justify-left", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  new_PL_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("New PL"),
                                _("Create New Playlist"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (new_PL_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-goto-bottom", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  export_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Export"),
                                _("Write Changes to Disk/iPod"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (export_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-stop", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  stop_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Stop"),
                                _("Stop Display Update"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);

  paned0 = gtk_hpaned_new ();
  gtk_widget_show (paned0);
  gtk_box_pack_start (GTK_BOX (vbox1), paned0, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (paned0), 150);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_paned_pack1 (GTK_PANED (paned0), scrolledwindow8, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow8), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  playlist_treeview = gtk_tree_view_new ();
  gtk_widget_show (playlist_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), playlist_treeview);
  gtk_widget_set_events (playlist_treeview, GDK_KEY_RELEASE_MASK);

  paned2 = gtk_vpaned_new ();
  gtk_widget_show (paned2);
  gtk_paned_pack2 (GTK_PANED (paned0), paned2, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (paned2), 180);

  paned1 = gtk_hpaned_new ();
  gtk_widget_show (paned1);
  gtk_paned_pack1 (GTK_PANED (paned2), paned1, FALSE, FALSE);

  sorttab0 = gtk_notebook_new ();
  gtk_widget_show (sorttab0);
  gtk_paned_pack1 (GTK_PANED (paned1), sorttab0, TRUE, TRUE);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (sorttab0), TRUE);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow9);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat0_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat0_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), st0_cat0_treeview);

  label8 = gtk_label_new (_("Artist"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 0), label8);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow12);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow12);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat1_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat1_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), st0_cat1_treeview);

  label9 = gtk_label_new (_("Album"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 1), label9);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  scrolledwindow13 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow13);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow13);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow13), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat2_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat2_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow13), st0_cat2_treeview);

  label10 = gtk_label_new (_("Genre"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 2), label10);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  scrolledwindow16 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow16);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow16);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow16), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat3_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat3_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow16), st0_cat3_treeview);

  label14 = gtk_label_new (_("Comp."));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 3), label14);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);

  scrolledwindow18 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow18);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow18);

  st0_cat4_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat4_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow18), st0_cat4_treeview);

  label23 = gtk_label_new (_("Title"));
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 4), label23);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);

  sorttab1 = gtk_notebook_new ();
  gtk_widget_show (sorttab1);
  gtk_paned_pack2 (GTK_PANED (paned1), sorttab1, TRUE, TRUE);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (sorttab1), TRUE);

  scrolledwindow15 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow15);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow15);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow15), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat0_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat0_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow15), st1_cat0_treeview);

  label11 = gtk_label_new (_("Artist"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 0), label11);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  scrolledwindow14 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow14);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow14);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow14), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat1_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat1_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow14), st1_cat1_treeview);

  label12 = gtk_label_new (_("Album"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 1), label12);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow10);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow10);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat2_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat2_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), st1_cat2_treeview);

  label13 = gtk_label_new (_("Genre"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 2), label13);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);

  scrolledwindow17 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow17);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow17);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow17), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat3_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat3_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow17), st1_cat3_treeview);

  label15 = gtk_label_new (_("Comp."));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 3), label15);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  scrolledwindow19 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow19);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow19);

  st1_cat4_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat4_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow19), st1_cat4_treeview);

  label24 = gtk_label_new (_("Title"));
  gtk_widget_show (label24);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 4), label24);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow11);
  gtk_paned_pack2 (GTK_PANED (paned2), scrolledwindow11, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  song_treeview = gtk_tree_view_new ();
  gtk_widget_show (song_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), song_treeview);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, TRUE, 0);

  gtkpod_status = gtk_statusbar_new ();
  gtk_widget_show (gtkpod_status);
  gtk_box_pack_start (GTK_BOX (hbox5), gtkpod_status, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (gtkpod_status), 1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (gtkpod_status), FALSE);

  songs_statusbar = gtk_statusbar_new ();
  gtk_widget_show (songs_statusbar);
  gtk_box_pack_start (GTK_BOX (hbox5), songs_statusbar, FALSE, TRUE, 0);
  gtk_widget_set_size_request (songs_statusbar, 175, 20);
  gtk_container_set_border_width (GTK_CONTAINER (songs_statusbar), 1);

  g_signal_connect ((gpointer) gtkpod, "delete_event",
                    G_CALLBACK (on_gtkpod_delete_event),
                    NULL);
  g_signal_connect ((gpointer) import_itunes_mi, "activate",
                    G_CALLBACK (on_import_itunes_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) add_files1, "activate",
                    G_CALLBACK (on_add_files1_activate),
                    NULL);
  g_signal_connect ((gpointer) add_directory1, "activate",
                    G_CALLBACK (on_add_directory1_activate),
                    NULL);
  g_signal_connect ((gpointer) add_playlist1, "activate",
                    G_CALLBACK (on_add_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) export_itunes1, "activate",
                    G_CALLBACK (on_export_itunes1_activate),
                    NULL);
  g_signal_connect ((gpointer) export_files_to_disk1, "activate",
                    G_CALLBACK (on_export_files_to_disk_activate),
                    NULL);
  g_signal_connect ((gpointer) offline_menu, "activate",
                    G_CALLBACK (on_offline1_activate),
                    NULL);
  g_signal_connect ((gpointer) ipod_directories, "activate",
                    G_CALLBACK (on_ipod_directories_menu),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) new_playlist1, "activate",
                    G_CALLBACK (on_new_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) songs_in_selected_playlist1, "activate",
                    G_CALLBACK (on_songs_in_selected_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) tab_entry_1, "activate",
                    G_CALLBACK (on_tab_entry_1_activate),
                    NULL);
  g_signal_connect ((gpointer) tab_entry_2, "activate",
                    G_CALLBACK (on_tab_entry_2_activate),
                    NULL);
  g_signal_connect ((gpointer) selected_songs1, "activate",
                    G_CALLBACK (on_selected_songs1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_playlist1, "activate",
                    G_CALLBACK (on_delete_playlist_menu),
                    NULL);
  g_signal_connect ((gpointer) sort_tab_2, "activate",
                    G_CALLBACK (on_delete_st0_activate),
                    NULL);
  g_signal_connect ((gpointer) sort_tab_3, "activate",
                    G_CALLBACK (on_delete_st1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_song, "activate",
                    G_CALLBACK (on_delete_song_menu),
                    NULL);
  g_signal_connect ((gpointer) edit_preferences1, "activate",
                    G_CALLBACK (on_edit_preferences1_activate),
                    NULL);
  g_signal_connect ((gpointer) alphabetize0_up, "activate",
                    G_CALLBACK (on_alphabetize0_up_menu),
                    NULL);
  g_signal_connect ((gpointer) alphabetize0_down, "activate",
                    G_CALLBACK (on_alphabetize0_down_menu),
                    NULL);
  g_signal_connect ((gpointer) re_init0, "activate",
                    G_CALLBACK (on_re_init0_menu),
                    NULL);
  g_signal_connect ((gpointer) alphabetize1_up, "activate",
                    G_CALLBACK (on_alphabetize1_up_menu),
                    NULL);
  g_signal_connect ((gpointer) alphabetize1_down, "activate",
                    G_CALLBACK (on_alphabetize1_down_menu),
                    NULL);
  g_signal_connect ((gpointer) re_init1, "activate",
                    G_CALLBACK (on_re_init1_menu),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) import_button, "clicked",
                    G_CALLBACK (on_import_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_files_button, "clicked",
                    G_CALLBACK (on_add_files1_button),
                    NULL);
  g_signal_connect ((gpointer) add_dirs_button, "clicked",
                    G_CALLBACK (on_add_directory1_button),
                    NULL);
  g_signal_connect ((gpointer) add_PL_button, "clicked",
                    G_CALLBACK (on_add_PL_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) new_PL_button, "clicked",
                    G_CALLBACK (on_new_playlist_button),
                    NULL);
  g_signal_connect ((gpointer) export_button, "clicked",
                    G_CALLBACK (on_export_itunes1_button),
                    NULL);
  g_signal_connect ((gpointer) stop_button, "clicked",
                    G_CALLBACK (on_stop_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) playlist_treeview, "drag_data_received",
                    G_CALLBACK (on_playlist_treeview_drag_data_received),
                    NULL);
  g_signal_connect_after ((gpointer) playlist_treeview, "key_release_event",
                          G_CALLBACK (on_playlist_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) sorttab0, "switch_page",
                    G_CALLBACK (on_sorttab_switch_page),
                    NULL);
  g_signal_connect ((gpointer) st0_cat0_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st0_cat0_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st0_cat1_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st0_cat1_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st0_cat2_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st0_cat2_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st0_cat3_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st0_cat3_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st0_cat4_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st0_cat4_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) sorttab1, "switch_page",
                    G_CALLBACK (on_sorttab_switch_page),
                    NULL);
  g_signal_connect ((gpointer) st1_cat0_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st1_cat0_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st1_cat1_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st1_cat1_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st1_cat2_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st1_cat2_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st1_cat3_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st1_cat3_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) st1_cat4_treeview, "drag_data_get",
                    G_CALLBACK (on_st_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) st1_cat4_treeview, "key_release_event",
                          G_CALLBACK (on_st_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) song_treeview, "drag_data_get",
                    G_CALLBACK (on_song_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) song_treeview, "key_release_event",
                          G_CALLBACK (on_song_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) song_treeview, "drag_data_received",
                    G_CALLBACK (on_song_treeview_drag_data_received),
                    NULL);
  g_signal_connect ((gpointer) gtkpod_status, "realize",
                    G_CALLBACK (on_gtkpod_status_realize),
                    NULL);
  g_signal_connect ((gpointer) songs_statusbar, "realize",
                    G_CALLBACK (on_songs_statusbar_realize),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtkpod, gtkpod, "gtkpod");
  GLADE_HOOKUP_OBJECT (gtkpod, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gtkpod, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem10, "menuitem10");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem10_menu, "menuitem10_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, import_itunes_mi, "import_itunes_mi");
  GLADE_HOOKUP_OBJECT (gtkpod, image311, "image311");
  GLADE_HOOKUP_OBJECT (gtkpod, add_files1, "add_files1");
  GLADE_HOOKUP_OBJECT (gtkpod, image312, "image312");
  GLADE_HOOKUP_OBJECT (gtkpod, add_directory1, "add_directory1");
  GLADE_HOOKUP_OBJECT (gtkpod, image313, "image313");
  GLADE_HOOKUP_OBJECT (gtkpod, add_playlist1, "add_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, image314, "image314");
  GLADE_HOOKUP_OBJECT (gtkpod, export_itunes1, "export_itunes1");
  GLADE_HOOKUP_OBJECT (gtkpod, image315, "image315");
  GLADE_HOOKUP_OBJECT (gtkpod, export_files_to_disk1, "export_files_to_disk1");
  GLADE_HOOKUP_OBJECT (gtkpod, image316, "image316");
  GLADE_HOOKUP_OBJECT (gtkpod, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (gtkpod, offline_menu, "offline_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, trennlinie1, "trennlinie1");
  GLADE_HOOKUP_OBJECT (gtkpod, ipod_directories, "ipod_directories");
  GLADE_HOOKUP_OBJECT (gtkpod, image317, "image317");
  GLADE_HOOKUP_OBJECT (gtkpod, trennlinie3, "trennlinie3");
  GLADE_HOOKUP_OBJECT (gtkpod, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem11, "menuitem11");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem11_menu, "menuitem11_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, new_playlist1, "new_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, image318, "image318");
  GLADE_HOOKUP_OBJECT (gtkpod, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (gtkpod, update_song_info_from_file1, "update_song_info_from_file1");
  GLADE_HOOKUP_OBJECT (gtkpod, image319, "image319");
  GLADE_HOOKUP_OBJECT (gtkpod, update_song_info_from_file1_menu, "update_song_info_from_file1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, songs_in_selected_playlist1, "songs_in_selected_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, songs_in_selected_tab_entry1, "songs_in_selected_tab_entry1");
  GLADE_HOOKUP_OBJECT (gtkpod, songs_in_selected_tab_entry1_menu, "songs_in_selected_tab_entry1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, tab_entry_1, "tab_entry_1");
  GLADE_HOOKUP_OBJECT (gtkpod, tab_entry_2, "tab_entry_2");
  GLADE_HOOKUP_OBJECT (gtkpod, selected_songs1, "selected_songs1");
  GLADE_HOOKUP_OBJECT (gtkpod, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_playlist1, "delete_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, image320, "image320");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_selected_tab_entry1, "delete_selected_tab_entry1");
  GLADE_HOOKUP_OBJECT (gtkpod, image321, "image321");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_selected_tab_entry1_menu, "delete_selected_tab_entry1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, sort_tab_2, "sort_tab_2");
  GLADE_HOOKUP_OBJECT (gtkpod, sort_tab_3, "sort_tab_3");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_song, "delete_song");
  GLADE_HOOKUP_OBJECT (gtkpod, image322, "image322");
  GLADE_HOOKUP_OBJECT (gtkpod, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (gtkpod, edit_preferences1, "edit_preferences1");
  GLADE_HOOKUP_OBJECT (gtkpod, image323, "image323");
  GLADE_HOOKUP_OBJECT (gtkpod, item1, "item1");
  GLADE_HOOKUP_OBJECT (gtkpod, item1_menu, "item1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, sort_tab_0, "sort_tab_0");
  GLADE_HOOKUP_OBJECT (gtkpod, sort_tab_0_menu, "sort_tab_0_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize0_up, "alphabetize0_up");
  GLADE_HOOKUP_OBJECT (gtkpod, image324, "image324");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize0_down, "alphabetize0_down");
  GLADE_HOOKUP_OBJECT (gtkpod, image325, "image325");
  GLADE_HOOKUP_OBJECT (gtkpod, re_init0, "re_init0");
  GLADE_HOOKUP_OBJECT (gtkpod, image326, "image326");
  GLADE_HOOKUP_OBJECT (gtkpod, sort_tab_1, "sort_tab_1");
  GLADE_HOOKUP_OBJECT (gtkpod, sort_tab_1_menu, "sort_tab_1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize1_up, "alphabetize1_up");
  GLADE_HOOKUP_OBJECT (gtkpod, image327, "image327");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize1_down, "alphabetize1_down");
  GLADE_HOOKUP_OBJECT (gtkpod, image328, "image328");
  GLADE_HOOKUP_OBJECT (gtkpod, re_init1, "re_init1");
  GLADE_HOOKUP_OBJECT (gtkpod, image329, "image329");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem13, "menuitem13");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem13_menu, "menuitem13_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, about1, "about1");
  GLADE_HOOKUP_OBJECT (gtkpod, image330, "image330");
  GLADE_HOOKUP_OBJECT (gtkpod, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (gtkpod, import_button, "import_button");
  GLADE_HOOKUP_OBJECT (gtkpod, add_files_button, "add_files_button");
  GLADE_HOOKUP_OBJECT (gtkpod, add_dirs_button, "add_dirs_button");
  GLADE_HOOKUP_OBJECT (gtkpod, add_PL_button, "add_PL_button");
  GLADE_HOOKUP_OBJECT (gtkpod, new_PL_button, "new_PL_button");
  GLADE_HOOKUP_OBJECT (gtkpod, export_button, "export_button");
  GLADE_HOOKUP_OBJECT (gtkpod, stop_button, "stop_button");
  GLADE_HOOKUP_OBJECT (gtkpod, paned0, "paned0");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow8, "scrolledwindow8");
  GLADE_HOOKUP_OBJECT (gtkpod, playlist_treeview, "playlist_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, paned2, "paned2");
  GLADE_HOOKUP_OBJECT (gtkpod, paned1, "paned1");
  GLADE_HOOKUP_OBJECT (gtkpod, sorttab0, "sorttab0");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat0_treeview, "st0_cat0_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label8, "label8");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat1_treeview, "st0_cat1_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label9, "label9");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow13, "scrolledwindow13");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat2_treeview, "st0_cat2_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label10, "label10");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow16, "scrolledwindow16");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat3_treeview, "st0_cat3_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label14, "label14");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow18, "scrolledwindow18");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat4_treeview, "st0_cat4_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label23, "label23");
  GLADE_HOOKUP_OBJECT (gtkpod, sorttab1, "sorttab1");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow15, "scrolledwindow15");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat0_treeview, "st1_cat0_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label11, "label11");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow14, "scrolledwindow14");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat1_treeview, "st1_cat1_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label12, "label12");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow10, "scrolledwindow10");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat2_treeview, "st1_cat2_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label13, "label13");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow17, "scrolledwindow17");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat3_treeview, "st1_cat3_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label15, "label15");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow19, "scrolledwindow19");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat4_treeview, "st1_cat4_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label24, "label24");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow11, "scrolledwindow11");
  GLADE_HOOKUP_OBJECT (gtkpod, song_treeview, "song_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gtkpod, gtkpod_status, "gtkpod_status");
  GLADE_HOOKUP_OBJECT (gtkpod, songs_statusbar, "songs_statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (gtkpod), accel_group);

  return gtkpod;
}

GtkWidget*
create_gtkpod_about_window (void)
{
  GtkWidget *gtkpod_about_window;
  GtkWidget *vbox2;
  GtkWidget *about_top_box;
  GtkWidget *about_label;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow2;
  GtkWidget *credits_textview;
  GtkWidget *label3;
  GtkWidget *scrolledwindow3;
  GtkWidget *translators_textview;
  GtkWidget *label4;
  GtkWidget *hbuttonbox2;
  GtkWidget *about_close;

  gtkpod_about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gtkpod_about_window, 350, 0);
  gtk_window_set_title (GTK_WINDOW (gtkpod_about_window), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (gtkpod_about_window), 450, 450);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (gtkpod_about_window), vbox2);

  about_top_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (about_top_box);
  gtk_box_pack_start (GTK_BOX (vbox2), about_top_box, FALSE, FALSE, 0);

  about_label = gtk_label_new ("");
  gtk_widget_show (about_label);
  gtk_box_pack_start (GTK_BOX (about_top_box), about_label, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (about_label), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox2), notebook1, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  credits_textview = gtk_text_view_new ();
  gtk_widget_show (credits_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), credits_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (credits_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (credits_textview), GTK_WRAP_WORD);

  label3 = gtk_label_new (_("Credits"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  translators_textview = gtk_text_view_new ();
  gtk_widget_show (translators_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), translators_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (translators_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (translators_textview), GTK_WRAP_WORD);

  label4 = gtk_label_new (_("Translators"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, FALSE, FALSE, 0);

  about_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (about_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), about_close);
  GTK_WIDGET_SET_FLAGS (about_close, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) gtkpod_about_window, "delete_event",
                            G_CALLBACK (on_about_window_close),
                            GTK_OBJECT (gtkpod_about_window));
  g_signal_connect_swapped ((gpointer) about_close, "clicked",
                            G_CALLBACK (on_about_window_close_button),
                            GTK_OBJECT (gtkpod_about_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtkpod_about_window, gtkpod_about_window, "gtkpod_about_window");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_top_box, "about_top_box");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_label, "about_label");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, credits_textview, "credits_textview");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, translators_textview, "translators_textview");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_close, "about_close");

  return gtkpod_about_window;
}

GtkWidget*
create_prefs_window (void)
{
  GtkWidget *prefs_window;
  GtkWidget *frame1;
  GtkWidget *vbox3;
  GtkWidget *hbox1;
  GtkWidget *label17;
  GtkWidget *cfg_mount_point;
  GtkWidget *hbox4;
  GtkWidget *label20;
  GtkWidget *charset_combo;
  GtkWidget *charset_combo_entry;
  GtkWidget *cfg_autoimport;
  GtkWidget *cfg_md5songs;
  GtkWidget *cfg_update_existing;
  GtkWidget *cfg_id3_write;
  GtkWidget *cfg_id3_writeall;
  GtkWidget *cfg_keep_backups;
  GtkWidget *cfg_write_extended;
  GtkWidget *cfg_block_display;
  GtkWidget *frame5;
  GtkWidget *hbox6;
  GtkWidget *vbox9;
  GtkWidget *tag_autoset1;
  GtkWidget *tag_autoset3;
  GtkWidget *vbox10;
  GtkWidget *tag_autoset2;
  GtkWidget *tag_autoset4;
  GtkWidget *vbox11;
  GtkWidget *tag_autoset0;
  GtkWidget *label22;
  GtkWidget *frame4;
  GtkWidget *vbox8;
  GtkWidget *cfg_mpl_autoselect;
  GtkWidget *cfg_st_autoselect0;
  GtkWidget *cfg_st_autoselect1;
  GtkWidget *label21;
  GtkWidget *frame3;
  GtkWidget *vbox7;
  GtkWidget *cfg_delete_playlist;
  GtkWidget *cfg_delete_track_from_playlist;
  GtkWidget *cfg_delete_track_from_ipod;
  GtkWidget *label19;
  GtkWidget *frame2;
  GtkWidget *hbox2;
  GtkWidget *vbox4;
  GtkWidget *cfg_song_list_artist;
  GtkWidget *cfg_song_list_genre;
  GtkWidget *vbox5;
  GtkWidget *cfg_song_list_album;
  GtkWidget *cfg_song_list_composer;
  GtkWidget *vbox12;
  GtkWidget *cfg_song_list_title;
  GtkWidget *cfg_song_list_track;
  GtkWidget *label18;
  GtkWidget *hbuttonbox3;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *label16;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  prefs_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (prefs_window), _("gtkpod Preferences"));

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (prefs_window), frame1);

  vbox3 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame1), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 2);

  hbox1 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, FALSE, TRUE, 0);

  label17 = gtk_label_new (_("iPod Mount Point:"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox1), label17, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  cfg_mount_point = gtk_entry_new ();
  gtk_widget_show (cfg_mount_point);
  gtk_box_pack_start (GTK_BOX (hbox1), cfg_mount_point, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_mount_point, _("Where you mounted your iPod's filesystem. Usually '/mnt/ipod/' or similar."), NULL);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox4, TRUE, TRUE, 0);

  label20 = gtk_label_new (_("Charset (ID3, files):"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox4), label20, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);

  charset_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (charset_combo)->popwin),
                     "GladeParentKey", charset_combo);
  gtk_widget_show (charset_combo);
  gtk_box_pack_start (GTK_BOX (hbox4), charset_combo, TRUE, TRUE, 0);

  charset_combo_entry = GTK_COMBO (charset_combo)->entry;
  gtk_widget_show (charset_combo_entry);
  gtk_tooltips_set_tip (tooltips, charset_combo_entry, _("gtkpod expects the ID3 tags and the filenames to be in the encoding specified here. You can change it for consecutive 'Add Files' and 'Add Dirs' operation. 'System Charset' is the charset used by your current locale."), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (charset_combo_entry), FALSE);

  cfg_autoimport = gtk_check_button_new_with_mnemonic (_("Automatically import iTunesDB on startup"));
  gtk_widget_show (cfg_autoimport);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_autoimport, FALSE, FALSE, 0);

  cfg_md5songs = gtk_check_button_new_with_mnemonic (_("Don't allow file duplication (slower import)"));
  gtk_widget_show (cfg_md5songs);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_md5songs, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_md5songs, _("Duplicate Recognition is based on a md5 hash over the file."), NULL);

  cfg_update_existing = gtk_check_button_new_with_mnemonic (_("When adding dirs/files, update information of\nexisting songs with identical filenames"));
  gtk_widget_show (cfg_update_existing);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_update_existing, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_update_existing, _("If the filename (full path) of an existing song matches that of a song to be added, this option allows you to update the information of the existing song rather than adding the song again. Please note that this option is different from the option above: duplicates are completely identical, having the same filename still allows for different ID3 tags. On export the updated song is copied to the iPod overwriting the old version."), NULL);

  cfg_id3_write = gtk_check_button_new_with_mnemonic (_("Write ID3 tags to disk when modified in gtkpod"));
  gtk_widget_show (cfg_id3_write);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_id3_write, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_id3_write, _("The tags are written to the files on your harddrive and on the ipod (if available)."), NULL);

  cfg_id3_writeall = gtk_check_button_new_with_mnemonic (_("Update all tags (not only changed ones)"));
  gtk_widget_show (cfg_id3_writeall);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_id3_writeall, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_id3_writeall, _("Normally only the tag you changed is written to disk."), NULL);

  cfg_keep_backups = gtk_check_button_new_with_mnemonic (_("Keep a backup of the iTunesDB in ~/.gtkpod/"));
  gtk_widget_show (cfg_keep_backups);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_keep_backups, FALSE, FALSE, 0);

  cfg_write_extended = gtk_check_button_new_with_mnemonic (_("Write extended information (PC filenames,\nMD5 hashes)"));
  gtk_widget_show (cfg_write_extended);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_write_extended, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_write_extended, _("Highly recommended for faster import when taking advantage of the duplication recognition. Also, having the PC filenames allows writing changed ID3 tags to disk, and even to reconstruct your ipod's contents in case of file system corruption (change the \"transferred=\" entries in your backuped database)."), NULL);

  cfg_block_display = gtk_check_button_new_with_mnemonic (_("Block display when changing playlist or tab\nentry (faster!)"));
  gtk_widget_show (cfg_block_display);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_block_display, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_block_display, _("The display can be blocked after changing a selection. The display update is faster, but you have to wait until it's finished."), NULL);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox3), frame5, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (frame5), hbox6);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox6), vbox9, TRUE, TRUE, 0);

  tag_autoset1 = gtk_check_button_new_with_mnemonic (_("Artist"));
  gtk_widget_show (tag_autoset1);
  gtk_box_pack_start (GTK_BOX (vbox9), tag_autoset1, FALSE, FALSE, 0);

  tag_autoset3 = gtk_check_button_new_with_mnemonic (_("Genre"));
  gtk_widget_show (tag_autoset3);
  gtk_box_pack_start (GTK_BOX (vbox9), tag_autoset3, FALSE, FALSE, 0);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (hbox6), vbox10, TRUE, TRUE, 0);

  tag_autoset2 = gtk_check_button_new_with_mnemonic (_("Album"));
  gtk_widget_show (tag_autoset2);
  gtk_box_pack_start (GTK_BOX (vbox10), tag_autoset2, FALSE, FALSE, 0);

  tag_autoset4 = gtk_check_button_new_with_mnemonic (_("Composer"));
  gtk_widget_show (tag_autoset4);
  gtk_box_pack_start (GTK_BOX (vbox10), tag_autoset4, FALSE, FALSE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox6), vbox11, TRUE, TRUE, 0);

  tag_autoset0 = gtk_check_button_new_with_mnemonic (_("Title"));
  gtk_widget_show (tag_autoset0);
  gtk_box_pack_start (GTK_BOX (vbox11), tag_autoset0, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("Automatically Set Empty ID3-Tags To Filename?"));
  gtk_widget_show (label22);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label22);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_LEFT);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox3), frame4, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame4), vbox8);

  cfg_mpl_autoselect = gtk_check_button_new_with_mnemonic (_("...master playlist"));
  gtk_widget_show (cfg_mpl_autoselect);
  gtk_box_pack_start (GTK_BOX (vbox8), cfg_mpl_autoselect, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_mpl_autoselect, _("If you don't select the master playlist automatically, the initial database import is much faster because the display dosn't have to be updated."), NULL);

  cfg_st_autoselect0 = gtk_check_button_new_with_mnemonic (_("...entry \"All\" in first sort tab"));
  gtk_widget_show (cfg_st_autoselect0);
  gtk_box_pack_start (GTK_BOX (vbox8), cfg_st_autoselect0, FALSE, FALSE, 0);

  cfg_st_autoselect1 = gtk_check_button_new_with_mnemonic (_("...entry \"All\" in second sort tab"));
  gtk_widget_show (cfg_st_autoselect1);
  gtk_box_pack_start (GTK_BOX (vbox8), cfg_st_autoselect1, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("Automatically select..."));
  gtk_widget_show (label21);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label21);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox3), frame3, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (frame3), vbox7);

  cfg_delete_playlist = gtk_check_button_new_with_mnemonic (_("Before removing playlists"));
  gtk_widget_show (cfg_delete_playlist);
  gtk_box_pack_start (GTK_BOX (vbox7), cfg_delete_playlist, FALSE, FALSE, 0);

  cfg_delete_track_from_playlist = gtk_check_button_new_with_mnemonic (_("Before removing tracks from playlist"));
  gtk_widget_show (cfg_delete_track_from_playlist);
  gtk_box_pack_start (GTK_BOX (vbox7), cfg_delete_track_from_playlist, FALSE, FALSE, 0);

  cfg_delete_track_from_ipod = gtk_check_button_new_with_mnemonic (_("Before removing tracks completely from iPod"));
  gtk_widget_show (cfg_delete_track_from_ipod);
  gtk_box_pack_start (GTK_BOX (vbox7), cfg_delete_track_from_ipod, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("Delete Confirmation "));
  gtk_widget_show (label19);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label19);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, FALSE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame2), hbox2);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox4, TRUE, TRUE, 0);

  cfg_song_list_artist = gtk_check_button_new_with_mnemonic (_("Artist"));
  gtk_widget_show (cfg_song_list_artist);
  gtk_box_pack_start (GTK_BOX (vbox4), cfg_song_list_artist, FALSE, FALSE, 0);

  cfg_song_list_genre = gtk_check_button_new_with_mnemonic (_("Genre"));
  gtk_widget_show (cfg_song_list_genre);
  gtk_box_pack_start (GTK_BOX (vbox4), cfg_song_list_genre, FALSE, FALSE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox5, TRUE, TRUE, 0);

  cfg_song_list_album = gtk_check_button_new_with_mnemonic (_("Album"));
  gtk_widget_show (cfg_song_list_album);
  gtk_box_pack_start (GTK_BOX (vbox5), cfg_song_list_album, FALSE, FALSE, 0);

  cfg_song_list_composer = gtk_check_button_new_with_mnemonic (_("Composer"));
  gtk_widget_show (cfg_song_list_composer);
  gtk_box_pack_start (GTK_BOX (vbox5), cfg_song_list_composer, FALSE, FALSE, 0);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox12, TRUE, TRUE, 0);

  cfg_song_list_title = gtk_check_button_new_with_mnemonic (_("Title"));
  gtk_widget_show (cfg_song_list_title);
  gtk_box_pack_start (GTK_BOX (vbox12), cfg_song_list_title, FALSE, FALSE, 0);

  cfg_song_list_track = gtk_check_button_new_with_mnemonic (_("Track Number (#)"));
  gtk_widget_show (cfg_song_list_track);
  gtk_box_pack_start (GTK_BOX (vbox12), cfg_song_list_track, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("Displayed Song Attributes "));
  gtk_widget_show (label18);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label18);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox3, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);

  button6 = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  button7 = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  label16 = gtk_label_new (_("gtkpod Preferences: "));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) prefs_window, "delete_event",
                    G_CALLBACK (on_prefs_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) cfg_mount_point, "changed",
                    G_CALLBACK (on_cfg_mount_point_changed),
                    NULL);
  g_signal_connect ((gpointer) charset_combo_entry, "changed",
                    G_CALLBACK (on_charset_combo_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) cfg_autoimport, "toggled",
                    G_CALLBACK (on_cfg_autoimport_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_md5songs, "toggled",
                    G_CALLBACK (on_cfg_md5songs_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_update_existing, "toggled",
                    G_CALLBACK (on_cfg_update_existing_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_id3_write, "toggled",
                    G_CALLBACK (on_cfg_id3_write_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_id3_writeall, "toggled",
                    G_CALLBACK (on_cfg_id3_writeall_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_keep_backups, "toggled",
                    G_CALLBACK (on_cfg_keep_backups_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_write_extended, "toggled",
                    G_CALLBACK (on_cfg_write_extended_info_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_block_display, "toggled",
                    G_CALLBACK (on_cfg_block_display_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_mpl_autoselect, "toggled",
                    G_CALLBACK (on_cfg_mpl_autoselect_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_playlist, "toggled",
                    G_CALLBACK (on_cfg_delete_playlist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_track_from_playlist, "toggled",
                    G_CALLBACK (on_cfg_delete_track_from_playlist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_track_from_ipod, "toggled",
                    G_CALLBACK (on_cfg_delete_track_from_ipod_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_artist, "toggled",
                    G_CALLBACK (on_cfg_song_list_artist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_genre, "toggled",
                    G_CALLBACK (on_cfg_song_list_genre_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_album, "toggled",
                    G_CALLBACK (on_cfg_song_list_album_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_composer, "toggled",
                    G_CALLBACK (on_cfg_song_list_composer_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_title, "toggled",
                    G_CALLBACK (on_cfg_song_list_title_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_track, "toggled",
                    G_CALLBACK (on_cfg_song_list_track_toggled),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_prefs_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_prefs_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefs_window, prefs_window, "prefs_window");
  GLADE_HOOKUP_OBJECT (prefs_window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (prefs_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_mount_point, "cfg_mount_point");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (prefs_window, label20, "label20");
  GLADE_HOOKUP_OBJECT (prefs_window, charset_combo, "charset_combo");
  GLADE_HOOKUP_OBJECT (prefs_window, charset_combo_entry, "charset_combo_entry");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_autoimport, "cfg_autoimport");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_md5songs, "cfg_md5songs");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_update_existing, "cfg_update_existing");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_id3_write, "cfg_id3_write");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_id3_writeall, "cfg_id3_writeall");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_keep_backups, "cfg_keep_backups");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_write_extended, "cfg_write_extended");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_block_display, "cfg_block_display");
  GLADE_HOOKUP_OBJECT (prefs_window, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (prefs_window, tag_autoset1, "tag_autoset1");
  GLADE_HOOKUP_OBJECT (prefs_window, tag_autoset3, "tag_autoset3");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (prefs_window, tag_autoset2, "tag_autoset2");
  GLADE_HOOKUP_OBJECT (prefs_window, tag_autoset4, "tag_autoset4");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (prefs_window, tag_autoset0, "tag_autoset0");
  GLADE_HOOKUP_OBJECT (prefs_window, label22, "label22");
  GLADE_HOOKUP_OBJECT (prefs_window, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_mpl_autoselect, "cfg_mpl_autoselect");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_st_autoselect0, "cfg_st_autoselect0");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_st_autoselect1, "cfg_st_autoselect1");
  GLADE_HOOKUP_OBJECT (prefs_window, label21, "label21");
  GLADE_HOOKUP_OBJECT (prefs_window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_delete_playlist, "cfg_delete_playlist");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_delete_track_from_playlist, "cfg_delete_track_from_playlist");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_delete_track_from_ipod, "cfg_delete_track_from_ipod");
  GLADE_HOOKUP_OBJECT (prefs_window, label19, "label19");
  GLADE_HOOKUP_OBJECT (prefs_window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_artist, "cfg_song_list_artist");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_genre, "cfg_song_list_genre");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_album, "cfg_song_list_album");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_composer, "cfg_song_list_composer");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_title, "cfg_song_list_title");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_track, "cfg_song_list_track");
  GLADE_HOOKUP_OBJECT (prefs_window, label18, "label18");
  GLADE_HOOKUP_OBJECT (prefs_window, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (prefs_window, button6, "button6");
  GLADE_HOOKUP_OBJECT (prefs_window, button7, "button7");
  GLADE_HOOKUP_OBJECT (prefs_window, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (prefs_window, tooltips, "tooltips");

  return prefs_window;
}

GtkWidget*
create_confirm_window (void)
{
  GtkWidget *confirm_window;
  GtkWidget *vbox6;
  GtkWidget *label;
  GtkWidget *vbox7;
  GtkWidget *scroller;
  GtkWidget *text;
  GtkWidget *hbox3;
  GtkWidget *never_again;
  GtkWidget *hbuttonbox4;
  GtkWidget *ok;
  GtkWidget *apply;
  GtkWidget *cancel;

  confirm_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (confirm_window), 6);
  gtk_window_set_title (GTK_WINDOW (confirm_window), _("window1"));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (confirm_window), vbox6);

  label = gtk_label_new (_("label21"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (vbox6), label, FALSE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label), 0.5, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  scroller = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scroller);
  gtk_box_pack_start (GTK_BOX (vbox7), scroller, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroller), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroller), GTK_SHADOW_IN);

  text = gtk_text_view_new ();
  gtk_widget_show (text);
  gtk_container_add (GTK_CONTAINER (scroller), text);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox3, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 2);

  never_again = gtk_check_button_new_with_mnemonic (_("Never ask this Again"));
  gtk_widget_show (never_again);
  gtk_box_pack_start (GTK_BOX (hbox3), never_again, FALSE, FALSE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox4, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox4), 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_SPREAD);

  ok = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), ok);
  GTK_WIDGET_SET_FLAGS (ok, GTK_CAN_DEFAULT);

  apply = gtk_button_new_with_mnemonic (_("Apply"));
  gtk_widget_show (apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), apply);
  GTK_WIDGET_SET_FLAGS (apply, GTK_CAN_DEFAULT);

  cancel = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), cancel);
  GTK_WIDGET_SET_FLAGS (cancel, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirm_window, confirm_window, "confirm_window");
  GLADE_HOOKUP_OBJECT (confirm_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (confirm_window, label, "label");
  GLADE_HOOKUP_OBJECT (confirm_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (confirm_window, scroller, "scroller");
  GLADE_HOOKUP_OBJECT (confirm_window, text, "text");
  GLADE_HOOKUP_OBJECT (confirm_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (confirm_window, never_again, "never_again");
  GLADE_HOOKUP_OBJECT (confirm_window, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (confirm_window, ok, "ok");
  GLADE_HOOKUP_OBJECT (confirm_window, apply, "apply");
  GLADE_HOOKUP_OBJECT (confirm_window, cancel, "cancel");

  return confirm_window;
}

