/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gtkpod (void)
{
  GtkWidget *gtkpod;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem10;
  GtkWidget *menuitem10_menu;
  GtkWidget *import_itunes_mi;
  GtkWidget *add_files1;
  GtkWidget *add_directory1;
  GtkWidget *export_itunes1;
  GtkWidget *separatormenuitem1;
  GtkWidget *offline_menu;
  GtkWidget *trennlinie1;
  GtkWidget *quit1;
  GtkWidget *menuitem11;
  GtkWidget *menuitem11_menu;
  GtkWidget *new_playlist1;
  GtkWidget *image10;
  GtkWidget *separator1;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *separator2;
  GtkWidget *edit_preferences1;
  GtkWidget *image11;
  GtkWidget *export_files_to_disk;
  GtkWidget *menuitem12;
  GtkWidget *menuitem13;
  GtkWidget *menuitem13_menu;
  GtkWidget *about1;
  GtkWidget *toolbar2;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *import_button;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow8;
  GtkWidget *playlist_treeview;
  GtkWidget *vpaned1;
  GtkWidget *hpaned2;
  GtkWidget *sorttab0;
  GtkWidget *scrolledwindow9;
  GtkWidget *st0_cat0_treeview;
  GtkWidget *label8;
  GtkWidget *scrolledwindow12;
  GtkWidget *st0_cat1_treeview;
  GtkWidget *label9;
  GtkWidget *scrolledwindow13;
  GtkWidget *st0_cat2_treeview;
  GtkWidget *label10;
  GtkWidget *scrolledwindow16;
  GtkWidget *st0_cat3_treeview;
  GtkWidget *label14;
  GtkWidget *sorttab1;
  GtkWidget *scrolledwindow15;
  GtkWidget *st1_cat0_treeview;
  GtkWidget *label11;
  GtkWidget *scrolledwindow14;
  GtkWidget *st1_cat1_treeview;
  GtkWidget *label12;
  GtkWidget *scrolledwindow10;
  GtkWidget *st1_cat2_treeview;
  GtkWidget *label13;
  GtkWidget *scrolledwindow17;
  GtkWidget *st1_cat3_treeview;
  GtkWidget *label15;
  GtkWidget *scrolledwindow11;
  GtkWidget *song_treeview;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  gtkpod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gtkpod), _("gtkpod"));
  gtk_window_set_default_size (GTK_WINDOW (gtkpod), 600, 500);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (gtkpod), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem10 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem10);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem10);

  menuitem10_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem10), menuitem10_menu);

  import_itunes_mi = gtk_menu_item_new_with_mnemonic (_("_Import iTunes"));
  gtk_widget_show (import_itunes_mi);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), import_itunes_mi);

  add_files1 = gtk_menu_item_new_with_mnemonic (_("Add _Files"));
  gtk_widget_show (add_files1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_files1);

  add_directory1 = gtk_menu_item_new_with_mnemonic (_("Add _Directory"));
  gtk_widget_show (add_directory1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_directory1);

  export_itunes1 = gtk_menu_item_new_with_mnemonic (_("_Export iTunes"));
  gtk_widget_show (export_itunes1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), export_itunes1);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  offline_menu = gtk_check_menu_item_new_with_mnemonic (_("Offline"));
  gtk_widget_show (offline_menu);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), offline_menu);

  trennlinie1 = gtk_menu_item_new ();
  gtk_widget_show (trennlinie1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), trennlinie1);
  gtk_widget_set_sensitive (trennlinie1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), quit1);

  menuitem11 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem11);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem11);

  menuitem11_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem11), menuitem11_menu);

  new_playlist1 = gtk_image_menu_item_new_with_mnemonic (_("_New Playlist"));
  gtk_widget_show (new_playlist1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), new_playlist1);

  image10 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image10);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_playlist1), image10);

  separator1 = gtk_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), delete1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  edit_preferences1 = gtk_image_menu_item_new_with_mnemonic (_("Edit Preferences"));
  gtk_widget_show (edit_preferences1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), edit_preferences1);
  gtk_widget_add_accelerator (edit_preferences1, "activate", accel_group,
                              GDK_p, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image11 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image11);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_preferences1), image11);

  export_files_to_disk = gtk_menu_item_new_with_mnemonic (_("Export Files to Disk"));
  gtk_widget_show (export_files_to_disk);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), export_files_to_disk);

  menuitem12 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem12);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem12);

  menuitem13 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem13);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem13);

  menuitem13_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem13), menuitem13_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem13_menu), about1);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar2, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-goto-top", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  import_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Import"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (import_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  button2 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Files"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (button2);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  button3 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Dirs"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (button3);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-justify-left", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("New PL"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (button4);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-goto-bottom", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  button5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Export"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (button5);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 150);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow8, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow8), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  playlist_treeview = gtk_tree_view_new ();
  gtk_widget_show (playlist_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), playlist_treeview);
  gtk_widget_set_events (playlist_treeview, GDK_KEY_RELEASE_MASK);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 180);

  hpaned2 = gtk_hpaned_new ();
  gtk_widget_show (hpaned2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), hpaned2, FALSE, FALSE);

  sorttab0 = gtk_notebook_new ();
  gtk_widget_show (sorttab0);
  gtk_paned_pack1 (GTK_PANED (hpaned2), sorttab0, TRUE, TRUE);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow9);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat0_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat0_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), st0_cat0_treeview);

  label8 = gtk_label_new (_("Artist"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 0), label8);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow12);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow12);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat1_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat1_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), st0_cat1_treeview);

  label9 = gtk_label_new (_("Album"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 1), label9);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  scrolledwindow13 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow13);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow13);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow13), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat2_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat2_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow13), st0_cat2_treeview);

  label10 = gtk_label_new (_("Genre"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 2), label10);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  scrolledwindow16 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow16);
  gtk_container_add (GTK_CONTAINER (sorttab0), scrolledwindow16);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow16), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st0_cat3_treeview = gtk_tree_view_new ();
  gtk_widget_show (st0_cat3_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow16), st0_cat3_treeview);

  label14 = gtk_label_new (_("Title"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab0), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab0), 3), label14);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);

  sorttab1 = gtk_notebook_new ();
  gtk_widget_show (sorttab1);
  gtk_paned_pack2 (GTK_PANED (hpaned2), sorttab1, TRUE, TRUE);

  scrolledwindow15 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow15);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow15);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow15), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat0_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat0_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow15), st1_cat0_treeview);

  label11 = gtk_label_new (_("Artist"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 0), label11);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  scrolledwindow14 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow14);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow14);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow14), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat1_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat1_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow14), st1_cat1_treeview);

  label12 = gtk_label_new (_("Album"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 1), label12);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow10);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow10);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat2_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat2_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), st1_cat2_treeview);

  label13 = gtk_label_new (_("Genre"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 2), label13);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);

  scrolledwindow17 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow17);
  gtk_container_add (GTK_CONTAINER (sorttab1), scrolledwindow17);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow17), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  st1_cat3_treeview = gtk_tree_view_new ();
  gtk_widget_show (st1_cat3_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow17), st1_cat3_treeview);

  label15 = gtk_label_new (_("Title"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (sorttab1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (sorttab1), 3), label15);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow11);
  gtk_paned_pack2 (GTK_PANED (vpaned1), scrolledwindow11, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  song_treeview = gtk_tree_view_new ();
  gtk_widget_show (song_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), song_treeview);
  gtk_widget_set_events (song_treeview, GDK_KEY_RELEASE_MASK);
  gtk_widget_add_accelerator (song_treeview, "select_all", accel_group,
                              GDK_a, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) gtkpod, "delete_event",
                    G_CALLBACK (on_gtkpod_delete_event),
                    NULL);
  g_signal_connect ((gpointer) import_itunes_mi, "activate",
                    G_CALLBACK (on_import_itunes_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) add_files1, "activate",
                    G_CALLBACK (on_add_files1_activate),
                    NULL);
  g_signal_connect ((gpointer) add_directory1, "activate",
                    G_CALLBACK (on_add_directory1_activate),
                    NULL);
  g_signal_connect ((gpointer) export_itunes1, "activate",
                    G_CALLBACK (on_export_itunes1_activate),
                    NULL);
  g_signal_connect ((gpointer) offline_menu, "activate",
                    G_CALLBACK (on_offline1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) new_playlist1, "activate",
                    G_CALLBACK (on_new_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_preferences1, "activate",
                    G_CALLBACK (on_edit_preferences1_activate),
                    NULL);
  g_signal_connect ((gpointer) export_files_to_disk, "activate",
                    G_CALLBACK (on_export_files_to_disk_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) import_button, "clicked",
                    G_CALLBACK (on_import_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_add_files1_button),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_add_directory1_button),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_new_playlist_button),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_export_itunes1_button),
                    NULL);
  g_signal_connect ((gpointer) playlist_treeview, "drag_data_received",
                    G_CALLBACK (on_playlist_treeview_drag_data_received),
                    NULL);
  g_signal_connect_after ((gpointer) playlist_treeview, "key_release_event",
                          G_CALLBACK (on_playlist_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) sorttab0, "switch_page",
                    G_CALLBACK (on_sorttab_switch_page),
                    NULL);
  g_signal_connect ((gpointer) sorttab1, "switch_page",
                    G_CALLBACK (on_sorttab_switch_page),
                    NULL);
  g_signal_connect ((gpointer) song_treeview, "drag_data_get",
                    G_CALLBACK (on_song_treeview_drag_data_get),
                    NULL);
  g_signal_connect_after ((gpointer) song_treeview, "key_release_event",
                          G_CALLBACK (on_song_treeview_key_release_event),
                          NULL);
  g_signal_connect ((gpointer) song_treeview, "drag_data_received",
                    G_CALLBACK (on_song_treeview_drag_data_received),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtkpod, gtkpod, "gtkpod");
  GLADE_HOOKUP_OBJECT (gtkpod, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gtkpod, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem10, "menuitem10");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem10_menu, "menuitem10_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, import_itunes_mi, "import_itunes_mi");
  GLADE_HOOKUP_OBJECT (gtkpod, add_files1, "add_files1");
  GLADE_HOOKUP_OBJECT (gtkpod, add_directory1, "add_directory1");
  GLADE_HOOKUP_OBJECT (gtkpod, export_itunes1, "export_itunes1");
  GLADE_HOOKUP_OBJECT (gtkpod, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (gtkpod, offline_menu, "offline_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, trennlinie1, "trennlinie1");
  GLADE_HOOKUP_OBJECT (gtkpod, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem11, "menuitem11");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem11_menu, "menuitem11_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, new_playlist1, "new_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, image10, "image10");
  GLADE_HOOKUP_OBJECT (gtkpod, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (gtkpod, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (gtkpod, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (gtkpod, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (gtkpod, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (gtkpod, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (gtkpod, edit_preferences1, "edit_preferences1");
  GLADE_HOOKUP_OBJECT (gtkpod, image11, "image11");
  GLADE_HOOKUP_OBJECT (gtkpod, export_files_to_disk, "export_files_to_disk");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem12, "menuitem12");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem13, "menuitem13");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem13_menu, "menuitem13_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, about1, "about1");
  GLADE_HOOKUP_OBJECT (gtkpod, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (gtkpod, import_button, "import_button");
  GLADE_HOOKUP_OBJECT (gtkpod, button2, "button2");
  GLADE_HOOKUP_OBJECT (gtkpod, button3, "button3");
  GLADE_HOOKUP_OBJECT (gtkpod, button4, "button4");
  GLADE_HOOKUP_OBJECT (gtkpod, button5, "button5");
  GLADE_HOOKUP_OBJECT (gtkpod, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow8, "scrolledwindow8");
  GLADE_HOOKUP_OBJECT (gtkpod, playlist_treeview, "playlist_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (gtkpod, hpaned2, "hpaned2");
  GLADE_HOOKUP_OBJECT (gtkpod, sorttab0, "sorttab0");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat0_treeview, "st0_cat0_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label8, "label8");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat1_treeview, "st0_cat1_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label9, "label9");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow13, "scrolledwindow13");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat2_treeview, "st0_cat2_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label10, "label10");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow16, "scrolledwindow16");
  GLADE_HOOKUP_OBJECT (gtkpod, st0_cat3_treeview, "st0_cat3_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label14, "label14");
  GLADE_HOOKUP_OBJECT (gtkpod, sorttab1, "sorttab1");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow15, "scrolledwindow15");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat0_treeview, "st1_cat0_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label11, "label11");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow14, "scrolledwindow14");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat1_treeview, "st1_cat1_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label12, "label12");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow10, "scrolledwindow10");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat2_treeview, "st1_cat2_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label13, "label13");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow17, "scrolledwindow17");
  GLADE_HOOKUP_OBJECT (gtkpod, st1_cat3_treeview, "st1_cat3_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, label15, "label15");
  GLADE_HOOKUP_OBJECT (gtkpod, scrolledwindow11, "scrolledwindow11");
  GLADE_HOOKUP_OBJECT (gtkpod, song_treeview, "song_treeview");
  GLADE_HOOKUP_OBJECT (gtkpod, statusbar1, "statusbar1");

  gtk_window_add_accel_group (GTK_WINDOW (gtkpod), accel_group);

  return gtkpod;
}

GtkWidget*
create_gtkpod_about_window (void)
{
  GtkWidget *gtkpod_about_window;
  GtkWidget *vbox2;
  GtkWidget *about_top_box;
  GtkWidget *about_label;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow2;
  GtkWidget *credits_textview;
  GtkWidget *label3;
  GtkWidget *scrolledwindow3;
  GtkWidget *translators_textview;
  GtkWidget *label4;
  GtkWidget *hbuttonbox2;
  GtkWidget *about_close;

  gtkpod_about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gtkpod_about_window, 350, 0);
  gtk_window_set_title (GTK_WINDOW (gtkpod_about_window), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (gtkpod_about_window), 450, 450);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (gtkpod_about_window), vbox2);

  about_top_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (about_top_box);
  gtk_box_pack_start (GTK_BOX (vbox2), about_top_box, FALSE, FALSE, 0);

  about_label = gtk_label_new ("");
  gtk_widget_show (about_label);
  gtk_box_pack_start (GTK_BOX (about_top_box), about_label, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (about_label), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox2), notebook1, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  credits_textview = gtk_text_view_new ();
  gtk_widget_show (credits_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), credits_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (credits_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (credits_textview), GTK_WRAP_WORD);

  label3 = gtk_label_new (_("Credits"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  translators_textview = gtk_text_view_new ();
  gtk_widget_show (translators_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), translators_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (translators_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (translators_textview), GTK_WRAP_WORD);

  label4 = gtk_label_new (_("Translators"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, FALSE, FALSE, 0);

  about_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (about_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), about_close);
  GTK_WIDGET_SET_FLAGS (about_close, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) gtkpod_about_window, "delete_event",
                            G_CALLBACK (on_about_window_close),
                            GTK_OBJECT (gtkpod_about_window));
  g_signal_connect_swapped ((gpointer) about_close, "clicked",
                            G_CALLBACK (on_about_window_close_button),
                            GTK_OBJECT (gtkpod_about_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtkpod_about_window, gtkpod_about_window, "gtkpod_about_window");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_top_box, "about_top_box");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_label, "about_label");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, credits_textview, "credits_textview");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, translators_textview, "translators_textview");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_close, "about_close");

  return gtkpod_about_window;
}

GtkWidget*
create_prefs_window (void)
{
  GtkWidget *prefs_window;
  GtkWidget *frame1;
  GtkWidget *vbox3;
  GtkWidget *hbox1;
  GtkWidget *label17;
  GtkWidget *cfg_mount_point;
  GtkWidget *hbox4;
  GtkWidget *label20;
  GtkWidget *locale_combo;
  GtkWidget *locale_combo_entry;
  GtkWidget *cfg_autoimport;
  GtkWidget *cfg_md5songs;
  GtkWidget *cfg_writeid3;
  GtkWidget *cfg_keep_backups;
  GtkWidget *cfg_write_extended;
  GtkWidget *frame2;
  GtkWidget *hbox2;
  GtkWidget *vbox4;
  GtkWidget *cfg_song_list_all;
  GtkWidget *cfg_song_list_artist;
  GtkWidget *cfg_song_list_album;
  GtkWidget *vbox5;
  GtkWidget *cfg_song_list_genre;
  GtkWidget *cfg_song_list_track;
  GtkWidget *label18;
  GtkWidget *frame3;
  GtkWidget *vbox7;
  GtkWidget *cfg_delete_playlist;
  GtkWidget *cfg_delete_track_from_playlist;
  GtkWidget *cfg_delete_track_from_ipod;
  GtkWidget *label19;
  GtkWidget *hbuttonbox3;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *label16;

  prefs_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (prefs_window), _("Gtkpod Preferences..."));

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (prefs_window), frame1);

  vbox3 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame1), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 2);

  hbox1 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, FALSE, TRUE, 0);

  label17 = gtk_label_new (_("Ipod Mount Point:"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox1), label17, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  cfg_mount_point = gtk_entry_new ();
  gtk_widget_show (cfg_mount_point);
  gtk_box_pack_start (GTK_BOX (hbox1), cfg_mount_point, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox4, TRUE, TRUE, 0);

  label20 = gtk_label_new (_("Locale for file operations:"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox4), label20, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);

  locale_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (locale_combo)->popwin),
                     "GladeParentKey", locale_combo);
  gtk_widget_show (locale_combo);
  gtk_box_pack_start (GTK_BOX (hbox4), locale_combo, TRUE, TRUE, 0);

  locale_combo_entry = GTK_COMBO (locale_combo)->entry;
  gtk_widget_show (locale_combo_entry);
  gtk_editable_set_editable (GTK_EDITABLE (locale_combo_entry), FALSE);

  cfg_autoimport = gtk_check_button_new_with_mnemonic (_("Automatically Import ItunesDB on startup"));
  gtk_widget_show (cfg_autoimport);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_autoimport, FALSE, FALSE, 0);

  cfg_md5songs = gtk_check_button_new_with_mnemonic (_("Don't Allow File Duplication(slower import)"));
  gtk_widget_show (cfg_md5songs);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_md5songs, FALSE, FALSE, 0);

  cfg_writeid3 = gtk_check_button_new_with_mnemonic (_("Change the ID3 Tags when modified in Gtkpod\n(on disk and on the ipod)"));
  gtk_widget_show (cfg_writeid3);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_writeid3, FALSE, FALSE, 0);

  cfg_keep_backups = gtk_check_button_new_with_mnemonic (_("Keep a backup of the iTunesDB in ~/.gtkpod/"));
  gtk_widget_show (cfg_keep_backups);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_keep_backups, FALSE, FALSE, 0);

  cfg_write_extended = gtk_check_button_new_with_mnemonic (_("Write extended information (PC filenames,\nMD5 hashes to disk)"));
  gtk_widget_show (cfg_write_extended);
  gtk_box_pack_start (GTK_BOX (vbox3), cfg_write_extended, FALSE, FALSE, 0);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, FALSE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame2), hbox2);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox4, TRUE, TRUE, 0);

  cfg_song_list_all = gtk_check_button_new_with_mnemonic (_("All Song Attributes"));
  gtk_widget_show (cfg_song_list_all);
  gtk_box_pack_start (GTK_BOX (vbox4), cfg_song_list_all, FALSE, FALSE, 0);

  cfg_song_list_artist = gtk_check_button_new_with_mnemonic (_("Artist"));
  gtk_widget_show (cfg_song_list_artist);
  gtk_box_pack_start (GTK_BOX (vbox4), cfg_song_list_artist, FALSE, FALSE, 0);

  cfg_song_list_album = gtk_check_button_new_with_mnemonic (_("Album"));
  gtk_widget_show (cfg_song_list_album);
  gtk_box_pack_start (GTK_BOX (vbox4), cfg_song_list_album, FALSE, FALSE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox5, TRUE, TRUE, 0);

  cfg_song_list_genre = gtk_check_button_new_with_mnemonic (_("Genre"));
  gtk_widget_show (cfg_song_list_genre);
  gtk_box_pack_start (GTK_BOX (vbox5), cfg_song_list_genre, FALSE, FALSE, 0);

  cfg_song_list_track = gtk_check_button_new_with_mnemonic (_("Track Number"));
  gtk_widget_show (cfg_song_list_track);
  gtk_box_pack_start (GTK_BOX (vbox5), cfg_song_list_track, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("Displayed Song Attributes"));
  gtk_widget_show (label18);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label18);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox3), frame3, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (frame3), vbox7);

  cfg_delete_playlist = gtk_check_button_new_with_mnemonic (_("Before Removing Playlists"));
  gtk_widget_show (cfg_delete_playlist);
  gtk_box_pack_start (GTK_BOX (vbox7), cfg_delete_playlist, FALSE, FALSE, 0);

  cfg_delete_track_from_playlist = gtk_check_button_new_with_mnemonic (_("Before Removing Tracks From Playlist"));
  gtk_widget_show (cfg_delete_track_from_playlist);
  gtk_box_pack_start (GTK_BOX (vbox7), cfg_delete_track_from_playlist, FALSE, FALSE, 0);

  cfg_delete_track_from_ipod = gtk_check_button_new_with_mnemonic (_("Before Removing Tracks Completely From Ipod"));
  gtk_widget_show (cfg_delete_track_from_ipod);
  gtk_box_pack_start (GTK_BOX (vbox7), cfg_delete_track_from_ipod, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("Delete Confirmation"));
  gtk_widget_show (label19);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label19);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox3, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);

  button6 = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  button7 = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  label16 = gtk_label_new (_("Gtkpod Preferences: "));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) prefs_window, "delete_event",
                    G_CALLBACK (on_prefs_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) cfg_mount_point, "changed",
                    G_CALLBACK (on_cfg_mount_point_changed),
                    NULL);
  g_signal_connect ((gpointer) locale_combo_entry, "changed",
                    G_CALLBACK (on_locale_combo_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) cfg_autoimport, "toggled",
                    G_CALLBACK (on_cfg_autoimport_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_md5songs, "toggled",
                    G_CALLBACK (on_cfg_md5songs_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_writeid3, "toggled",
                    G_CALLBACK (on_cfg_writeid3_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_keep_backups, "toggled",
                    G_CALLBACK (on_cfg_keep_backups_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_write_extended, "toggled",
                    G_CALLBACK (on_cfg_write_extended_info_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_all, "toggled",
                    G_CALLBACK (on_cfg_song_list_all_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_artist, "toggled",
                    G_CALLBACK (on_cfg_song_list_artist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_album, "toggled",
                    G_CALLBACK (on_cfg_song_list_album_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_genre, "toggled",
                    G_CALLBACK (on_cfg_song_list_genre_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_song_list_track, "toggled",
                    G_CALLBACK (on_cfg_song_list_track_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_playlist, "toggled",
                    G_CALLBACK (on_cfg_delete_playlist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_track_from_playlist, "toggled",
                    G_CALLBACK (on_cfg_delete_track_from_playlist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_track_from_ipod, "toggled",
                    G_CALLBACK (on_cfg_delete_track_from_ipod_toggled),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_prefs_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_prefs_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefs_window, prefs_window, "prefs_window");
  GLADE_HOOKUP_OBJECT (prefs_window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (prefs_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_mount_point, "cfg_mount_point");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (prefs_window, label20, "label20");
  GLADE_HOOKUP_OBJECT (prefs_window, locale_combo, "locale_combo");
  GLADE_HOOKUP_OBJECT (prefs_window, locale_combo_entry, "locale_combo_entry");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_autoimport, "cfg_autoimport");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_md5songs, "cfg_md5songs");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_writeid3, "cfg_writeid3");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_keep_backups, "cfg_keep_backups");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_write_extended, "cfg_write_extended");
  GLADE_HOOKUP_OBJECT (prefs_window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (prefs_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_all, "cfg_song_list_all");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_artist, "cfg_song_list_artist");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_album, "cfg_song_list_album");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_genre, "cfg_song_list_genre");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_song_list_track, "cfg_song_list_track");
  GLADE_HOOKUP_OBJECT (prefs_window, label18, "label18");
  GLADE_HOOKUP_OBJECT (prefs_window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (prefs_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_delete_playlist, "cfg_delete_playlist");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_delete_track_from_playlist, "cfg_delete_track_from_playlist");
  GLADE_HOOKUP_OBJECT (prefs_window, cfg_delete_track_from_ipod, "cfg_delete_track_from_ipod");
  GLADE_HOOKUP_OBJECT (prefs_window, label19, "label19");
  GLADE_HOOKUP_OBJECT (prefs_window, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (prefs_window, button6, "button6");
  GLADE_HOOKUP_OBJECT (prefs_window, button7, "button7");
  GLADE_HOOKUP_OBJECT (prefs_window, label16, "label16");

  return prefs_window;
}

GtkWidget*
create_delete_confirmation (void)
{
  GtkWidget *delete_confirmation;
  GtkWidget *vbox6;
  GtkWidget *msg_label;
  GtkWidget *hbox3;
  GtkWidget *prefs_request;
  GtkWidget *hbuttonbox4;
  GtkWidget *delete_ok;
  GtkWidget *delete_cancel;

  delete_confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (delete_confirmation), 6);
  gtk_window_set_title (GTK_WINDOW (delete_confirmation), _("window1"));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (delete_confirmation), vbox6);

  msg_label = gtk_label_new (_("Are You Sure"));
  gtk_widget_show (msg_label);
  gtk_box_pack_start (GTK_BOX (vbox6), msg_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (msg_label), GTK_JUSTIFY_LEFT);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox3, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 2);

  prefs_request = gtk_check_button_new_with_mnemonic (_("Never ask this Again"));
  gtk_widget_show (prefs_request);
  gtk_box_pack_start (GTK_BOX (hbox3), prefs_request, FALSE, FALSE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox4, FALSE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox4), 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_SPREAD);

  delete_ok = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (delete_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), delete_ok);
  GTK_WIDGET_SET_FLAGS (delete_ok, GTK_CAN_DEFAULT);

  delete_cancel = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (delete_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), delete_cancel);
  GTK_WIDGET_SET_FLAGS (delete_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) delete_confirmation, "delete_event",
                    G_CALLBACK (on_delete_confirmation_delete_event),
                    NULL);
  g_signal_connect ((gpointer) prefs_request, "toggled",
                    G_CALLBACK (on_prefs_request_toggled),
                    NULL);
  g_signal_connect ((gpointer) delete_ok, "clicked",
                    G_CALLBACK (on_delete_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete_cancel, "clicked",
                    G_CALLBACK (on_delete_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (delete_confirmation, delete_confirmation, "delete_confirmation");
  GLADE_HOOKUP_OBJECT (delete_confirmation, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (delete_confirmation, msg_label, "msg_label");
  GLADE_HOOKUP_OBJECT (delete_confirmation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (delete_confirmation, prefs_request, "prefs_request");
  GLADE_HOOKUP_OBJECT (delete_confirmation, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (delete_confirmation, delete_ok, "delete_ok");
  GLADE_HOOKUP_OBJECT (delete_confirmation, delete_cancel, "delete_cancel");

  return delete_confirmation;
}

