/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gtkpod (void)
{
  GtkWidget *gtkpod;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *menuitem10;
  GtkWidget *menuitem10_menu;
  GtkWidget *import_itunes_mi;
  GtkWidget *image897;
  GtkWidget *add_files1;
  GtkWidget *image898;
  GtkWidget *add_directory1;
  GtkWidget *image899;
  GtkWidget *add_playlist1;
  GtkWidget *image900;
  GtkWidget *export_itunes1;
  GtkWidget *image901;
  GtkWidget *export_menu;
  GtkWidget *image902;
  GtkWidget *export_menu_menu;
  GtkWidget *export_playlist;
  GtkWidget *export_tab_entry_menu;
  GtkWidget *export_songs;
  GtkWidget *separatormenuitem1;
  GtkWidget *offline_menu;
  GtkWidget *trennlinie1;
  GtkWidget *ipod_directories;
  GtkWidget *image903;
  GtkWidget *trennlinie3;
  GtkWidget *quit1;
  GtkWidget *menuitem11;
  GtkWidget *menuitem11_menu;
  GtkWidget *new_playlist1;
  GtkWidget *image904;
  GtkWidget *separator1;
  GtkWidget *alphabetize0_menu;
  GtkWidget *image905;
  GtkWidget *alphabetize0_menu_menu;
  GtkWidget *alpha_playlists0;
  GtkWidget *alpha_sort_tab0;
  GtkWidget *alphabetize1_menu;
  GtkWidget *image906;
  GtkWidget *alphabetize1_menu_menu;
  GtkWidget *alpha_playlists1;
  GtkWidget *alpha_sort_tab1;
  GtkWidget *reset_sorting;
  GtkWidget *image907;
  GtkWidget *save_song_order1;
  GtkWidget *image908;
  GtkWidget *separator3;
  GtkWidget *update_menu;
  GtkWidget *image909;
  GtkWidget *update_menu_menu;
  GtkWidget *update_playlist_menu;
  GtkWidget *update_tab_entry_menu;
  GtkWidget *update_songs_menu;
  GtkWidget *separator4;
  GtkWidget *delete_menu;
  GtkWidget *image910;
  GtkWidget *delete_menu_menu;
  GtkWidget *delete_playlist_menu;
  GtkWidget *delete_tab_entry_menu;
  GtkWidget *delete_songs_menu;
  GtkWidget *separator2;
  GtkWidget *edit_preferences1;
  GtkWidget *image911;
  GtkWidget *item1;
  GtkWidget *item1_menu;
  GtkWidget *toolbar_menu;
  GtkWidget *more_sort_tabs;
  GtkWidget *image912;
  GtkWidget *less_sort_tabs;
  GtkWidget *image913;
  GtkWidget *arrange_sort_tabs;
  GtkWidget *tools1;
  GtkWidget *tools1_menu;
  GtkWidget *play_menu;
  GtkWidget *image914;
  GtkWidget *play_menu_menu;
  GtkWidget *play_playlist_menu;
  GtkWidget *play_tab_entry_menu;
  GtkWidget *play_songs_menu;
  GtkWidget *enqueue_menu;
  GtkWidget *image915;
  GtkWidget *enqueue_menu_menu;
  GtkWidget *enqueue_playlist_menu;
  GtkWidget *enqueue_tab_entry_menu;
  GtkWidget *enqueue_songs_menu;
  GtkWidget *menuitem13;
  GtkWidget *menuitem13_menu;
  GtkWidget *about1;
  GtkWidget *image916;
  GtkWidget *toolbar;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *import_button;
  GtkWidget *add_files_button;
  GtkWidget *add_dirs_button;
  GtkWidget *add_PL_button;
  GtkWidget *new_PL_button;
  GtkWidget *export_button;
  GtkWidget *stop_button;
  GtkWidget *paned0;
  GtkWidget *playlist_window;
  GtkWidget *paned1;
  GtkWidget *song_window;
  GtkWidget *paned2;
  GtkWidget *gtkpod_status;
  GtkWidget *hbox13;
  GtkWidget *space_statusbar;
  GtkWidget *songs_statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  gtkpod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gtkpod), _("gtkpod"));
  gtk_window_set_default_size (GTK_WINDOW (gtkpod), 600, 500);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (gtkpod), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);

  menuitem10 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem10);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem10);

  menuitem10_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem10), menuitem10_menu);

  import_itunes_mi = gtk_image_menu_item_new_with_mnemonic (_("_Import iTunes"));
  gtk_widget_show (import_itunes_mi);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), import_itunes_mi);

  image897 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image897);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (import_itunes_mi), image897);

  add_files1 = gtk_image_menu_item_new_with_mnemonic (_("Add _Files"));
  gtk_widget_show (add_files1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_files1);

  image898 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image898);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_files1), image898);

  add_directory1 = gtk_image_menu_item_new_with_mnemonic (_("Add _Directory"));
  gtk_widget_show (add_directory1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_directory1);

  image899 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image899);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_directory1), image899);

  add_playlist1 = gtk_image_menu_item_new_with_mnemonic (_("Add _Playlist"));
  gtk_widget_show (add_playlist1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), add_playlist1);

  image900 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image900);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_playlist1), image900);

  export_itunes1 = gtk_image_menu_item_new_with_mnemonic (_("_Export iTunes"));
  gtk_widget_show (export_itunes1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), export_itunes1);

  image901 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image901);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (export_itunes1), image901);

  export_menu = gtk_image_menu_item_new_with_mnemonic (_("Export Files _to Disk"));
  gtk_widget_show (export_menu);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), export_menu);

  image902 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image902);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (export_menu), image902);

  export_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (export_menu), export_menu_menu);

  export_playlist = gtk_menu_item_new_with_mnemonic (_("Selected _Playlist"));
  gtk_widget_show (export_playlist);
  gtk_container_add (GTK_CONTAINER (export_menu_menu), export_playlist);

  export_tab_entry_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Tab Entry"));
  gtk_widget_show (export_tab_entry_menu);
  gtk_container_add (GTK_CONTAINER (export_menu_menu), export_tab_entry_menu);

  export_songs = gtk_menu_item_new_with_mnemonic (_("Selected _Songs"));
  gtk_widget_show (export_songs);
  gtk_container_add (GTK_CONTAINER (export_menu_menu), export_songs);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  offline_menu = gtk_check_menu_item_new_with_mnemonic (_("_Offline"));
  gtk_widget_show (offline_menu);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), offline_menu);

  trennlinie1 = gtk_menu_item_new ();
  gtk_widget_show (trennlinie1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), trennlinie1);
  gtk_widget_set_sensitive (trennlinie1, FALSE);

  ipod_directories = gtk_image_menu_item_new_with_mnemonic (_("_Create iPod's Directories"));
  gtk_widget_show (ipod_directories);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), ipod_directories);

  image903 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image903);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ipod_directories), image903);

  trennlinie3 = gtk_menu_item_new ();
  gtk_widget_show (trennlinie3);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), trennlinie3);
  gtk_widget_set_sensitive (trennlinie3, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem10_menu), quit1);

  menuitem11 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem11);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem11);

  menuitem11_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem11), menuitem11_menu);

  new_playlist1 = gtk_image_menu_item_new_with_mnemonic (_("_New Playlist"));
  gtk_widget_show (new_playlist1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), new_playlist1);

  image904 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image904);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_playlist1), image904);

  separator1 = gtk_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  alphabetize0_menu = gtk_image_menu_item_new_with_mnemonic (_("_Alphabetize"));
  gtk_widget_show (alphabetize0_menu);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), alphabetize0_menu);

  image905 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image905);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (alphabetize0_menu), image905);

  alphabetize0_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (alphabetize0_menu), alphabetize0_menu_menu);

  alpha_playlists0 = gtk_menu_item_new_with_mnemonic (_("_Playlists"));
  gtk_widget_show (alpha_playlists0);
  gtk_container_add (GTK_CONTAINER (alphabetize0_menu_menu), alpha_playlists0);

  alpha_sort_tab0 = gtk_menu_item_new_with_mnemonic (_("_Sort Tab"));
  gtk_widget_show (alpha_sort_tab0);
  gtk_container_add (GTK_CONTAINER (alphabetize0_menu_menu), alpha_sort_tab0);

  alphabetize1_menu = gtk_image_menu_item_new_with_mnemonic (_("Alphabeti_ze"));
  gtk_widget_show (alphabetize1_menu);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), alphabetize1_menu);

  image906 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image906);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (alphabetize1_menu), image906);

  alphabetize1_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (alphabetize1_menu), alphabetize1_menu_menu);

  alpha_playlists1 = gtk_menu_item_new_with_mnemonic (_("_Playlists"));
  gtk_widget_show (alpha_playlists1);
  gtk_container_add (GTK_CONTAINER (alphabetize1_menu_menu), alpha_playlists1);

  alpha_sort_tab1 = gtk_menu_item_new_with_mnemonic (_("_Sort Tab"));
  gtk_widget_show (alpha_sort_tab1);
  gtk_container_add (GTK_CONTAINER (alphabetize1_menu_menu), alpha_sort_tab1);

  reset_sorting = gtk_image_menu_item_new_with_mnemonic (_("_Reset Sorting"));
  gtk_widget_show (reset_sorting);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), reset_sorting);

  image907 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image907);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (reset_sorting), image907);

  save_song_order1 = gtk_image_menu_item_new_with_mnemonic (_("_Save Displayed Song Order"));
  gtk_widget_show (save_song_order1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), save_song_order1);

  image908 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image908);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save_song_order1), image908);

  separator3 = gtk_menu_item_new ();
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  update_menu = gtk_image_menu_item_new_with_mnemonic (_("_Update Songs from File"));
  gtk_widget_show (update_menu);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), update_menu);

  image909 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image909);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (update_menu), image909);

  update_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (update_menu), update_menu_menu);

  update_playlist_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Playlist"));
  gtk_widget_show (update_playlist_menu);
  gtk_container_add (GTK_CONTAINER (update_menu_menu), update_playlist_menu);

  update_tab_entry_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Tab Entry"));
  gtk_widget_show (update_tab_entry_menu);
  gtk_container_add (GTK_CONTAINER (update_menu_menu), update_tab_entry_menu);

  update_songs_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Songs"));
  gtk_widget_show (update_songs_menu);
  gtk_container_add (GTK_CONTAINER (update_menu_menu), update_songs_menu);

  separator4 = gtk_menu_item_new ();
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  delete_menu = gtk_image_menu_item_new_with_mnemonic (_("_Delete"));
  gtk_widget_show (delete_menu);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), delete_menu);

  image910 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image910);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (delete_menu), image910);

  delete_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (delete_menu), delete_menu_menu);

  delete_playlist_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Playlist"));
  gtk_widget_show (delete_playlist_menu);
  gtk_container_add (GTK_CONTAINER (delete_menu_menu), delete_playlist_menu);

  delete_tab_entry_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Tab Entry"));
  gtk_widget_show (delete_tab_entry_menu);
  gtk_container_add (GTK_CONTAINER (delete_menu_menu), delete_tab_entry_menu);

  delete_songs_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Songs"));
  gtk_widget_show (delete_songs_menu);
  gtk_container_add (GTK_CONTAINER (delete_menu_menu), delete_songs_menu);

  separator2 = gtk_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  edit_preferences1 = gtk_image_menu_item_new_with_mnemonic (_("_Edit Preferences"));
  gtk_widget_show (edit_preferences1);
  gtk_container_add (GTK_CONTAINER (menuitem11_menu), edit_preferences1);
  gtk_widget_add_accelerator (edit_preferences1, "activate", accel_group,
                              GDK_p, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image911 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image911);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (edit_preferences1), image911);

  item1 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (item1);
  gtk_container_add (GTK_CONTAINER (menubar), item1);

  item1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (item1), item1_menu);

  toolbar_menu = gtk_check_menu_item_new_with_mnemonic (_("_Toolbar"));
  gtk_widget_show (toolbar_menu);
  gtk_container_add (GTK_CONTAINER (item1_menu), toolbar_menu);

  more_sort_tabs = gtk_image_menu_item_new_with_mnemonic (_("_More Sort Tabs"));
  gtk_widget_show (more_sort_tabs);
  gtk_container_add (GTK_CONTAINER (item1_menu), more_sort_tabs);

  image912 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image912);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (more_sort_tabs), image912);

  less_sort_tabs = gtk_image_menu_item_new_with_mnemonic (_("_Less Sort Tabs"));
  gtk_widget_show (less_sort_tabs);
  gtk_container_add (GTK_CONTAINER (item1_menu), less_sort_tabs);

  image913 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image913);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (less_sort_tabs), image913);

  arrange_sort_tabs = gtk_menu_item_new_with_mnemonic (_("_Arrange Sort Tabs"));
  gtk_widget_show (arrange_sort_tabs);
  gtk_container_add (GTK_CONTAINER (item1_menu), arrange_sort_tabs);

  tools1 = gtk_menu_item_new_with_mnemonic (_("Tools"));
  gtk_widget_show (tools1);
  gtk_container_add (GTK_CONTAINER (menubar), tools1);

  tools1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (tools1), tools1_menu);

  play_menu = gtk_image_menu_item_new_with_mnemonic (_("_Play Now"));
  gtk_widget_show (play_menu);
  gtk_container_add (GTK_CONTAINER (tools1_menu), play_menu);

  image914 = gtk_image_new_from_stock ("gtk-cdrom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image914);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (play_menu), image914);

  play_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (play_menu), play_menu_menu);

  play_playlist_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Playlist"));
  gtk_widget_show (play_playlist_menu);
  gtk_container_add (GTK_CONTAINER (play_menu_menu), play_playlist_menu);

  play_tab_entry_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Tab Entry"));
  gtk_widget_show (play_tab_entry_menu);
  gtk_container_add (GTK_CONTAINER (play_menu_menu), play_tab_entry_menu);

  play_songs_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Songs"));
  gtk_widget_show (play_songs_menu);
  gtk_container_add (GTK_CONTAINER (play_menu_menu), play_songs_menu);

  enqueue_menu = gtk_image_menu_item_new_with_mnemonic (_("_Enqueue"));
  gtk_widget_show (enqueue_menu);
  gtk_container_add (GTK_CONTAINER (tools1_menu), enqueue_menu);

  image915 = gtk_image_new_from_stock ("gtk-cdrom", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image915);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (enqueue_menu), image915);

  enqueue_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (enqueue_menu), enqueue_menu_menu);

  enqueue_playlist_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Playlist"));
  gtk_widget_show (enqueue_playlist_menu);
  gtk_container_add (GTK_CONTAINER (enqueue_menu_menu), enqueue_playlist_menu);

  enqueue_tab_entry_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Tab Entry"));
  gtk_widget_show (enqueue_tab_entry_menu);
  gtk_container_add (GTK_CONTAINER (enqueue_menu_menu), enqueue_tab_entry_menu);

  enqueue_songs_menu = gtk_menu_item_new_with_mnemonic (_("Selected _Songs"));
  gtk_widget_show (enqueue_songs_menu);
  gtk_container_add (GTK_CONTAINER (enqueue_menu_menu), enqueue_songs_menu);

  menuitem13 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem13);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem13);

  menuitem13_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem13), menuitem13_menu);

  about1 = gtk_image_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem13_menu), about1);

  image916 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image916);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image916);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-goto-top", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  import_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Import"),
                                _("Read Existing Database from Disk/iPod"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (import_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  add_files_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Files"),
                                _("Add Files or Directories"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (add_files_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  add_dirs_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Dirs"),
                                _("Add Directories Recursively"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (add_dirs_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  add_PL_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Playlist"),
                                _("Add playlist from file"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (add_PL_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-justify-left", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  new_PL_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("New PL"),
                                _("Create New Playlist"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (new_PL_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-goto-bottom", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  export_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Export"),
                                _("Write Changes to Disk/iPod"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);
  gtk_widget_show (export_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-stop", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar)));
  stop_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Stop"),
                                _("Stop Display Update"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar)->children)->data))->label), TRUE);

  paned0 = gtk_hpaned_new ();
  gtk_widget_show (paned0);
  gtk_box_pack_start (GTK_BOX (vbox1), paned0, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (paned0), 150);

  playlist_window = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (playlist_window);
  gtk_paned_pack1 (GTK_PANED (paned0), playlist_window, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (playlist_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  paned1 = gtk_vpaned_new ();
  gtk_widget_show (paned1);
  gtk_paned_pack2 (GTK_PANED (paned0), paned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (paned1), 180);

  song_window = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (song_window);
  gtk_paned_pack2 (GTK_PANED (paned1), song_window, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (song_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  paned2 = gtk_hpaned_new ();
  gtk_widget_show (paned2);
  gtk_box_pack_start (GTK_BOX (vbox1), paned2, FALSE, TRUE, 0);

  gtkpod_status = gtk_statusbar_new ();
  gtk_widget_show (gtkpod_status);
  gtk_paned_pack1 (GTK_PANED (paned2), gtkpod_status, TRUE, FALSE);
  gtk_widget_set_size_request (gtkpod_status, 300, 20);
  gtk_container_set_border_width (GTK_CONTAINER (gtkpod_status), 1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (gtkpod_status), FALSE);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_paned_pack2 (GTK_PANED (paned2), hbox13, FALSE, TRUE);

  space_statusbar = gtk_statusbar_new ();
  gtk_widget_show (space_statusbar);
  gtk_box_pack_start (GTK_BOX (hbox13), space_statusbar, TRUE, TRUE, 0);
  gtk_widget_set_size_request (space_statusbar, 80, 20);
  gtk_container_set_border_width (GTK_CONTAINER (space_statusbar), 1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (space_statusbar), FALSE);

  songs_statusbar = gtk_statusbar_new ();
  gtk_widget_show (songs_statusbar);
  gtk_box_pack_start (GTK_BOX (hbox13), songs_statusbar, TRUE, TRUE, 0);
  gtk_widget_set_size_request (songs_statusbar, 175, 20);
  gtk_container_set_border_width (GTK_CONTAINER (songs_statusbar), 1);

  g_signal_connect ((gpointer) gtkpod, "delete_event",
                    G_CALLBACK (on_gtkpod_delete_event),
                    NULL);
  g_signal_connect ((gpointer) import_itunes_mi, "activate",
                    G_CALLBACK (on_import_itunes_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) add_files1, "activate",
                    G_CALLBACK (on_add_files1_activate),
                    NULL);
  g_signal_connect ((gpointer) add_directory1, "activate",
                    G_CALLBACK (on_add_directory1_activate),
                    NULL);
  g_signal_connect ((gpointer) add_playlist1, "activate",
                    G_CALLBACK (on_add_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) export_itunes1, "activate",
                    G_CALLBACK (on_export_itunes1_activate),
                    NULL);
  g_signal_connect ((gpointer) export_playlist, "activate",
                    G_CALLBACK (on_export_playlist_activate),
                    NULL);
  g_signal_connect ((gpointer) export_tab_entry_menu, "activate",
                    G_CALLBACK (on_export_tab_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) export_songs, "activate",
                    G_CALLBACK (on_export_songs_activate),
                    NULL);
  g_signal_connect ((gpointer) offline_menu, "activate",
                    G_CALLBACK (on_offline1_activate),
                    NULL);
  g_signal_connect ((gpointer) ipod_directories, "activate",
                    G_CALLBACK (on_ipod_directories_menu),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) new_playlist1, "activate",
                    G_CALLBACK (on_new_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) alpha_playlists0, "activate",
                    G_CALLBACK (on_alpha_playlists0_activate),
                    NULL);
  g_signal_connect ((gpointer) alpha_sort_tab0, "activate",
                    G_CALLBACK (on_alpha_sort_tab0_activate),
                    NULL);
  g_signal_connect ((gpointer) alpha_playlists1, "activate",
                    G_CALLBACK (on_alpha_playlist1_activate),
                    NULL);
  g_signal_connect ((gpointer) alpha_sort_tab1, "activate",
                    G_CALLBACK (on_alpha_sort_tab1_activate),
                    NULL);
  g_signal_connect ((gpointer) reset_sorting, "activate",
                    G_CALLBACK (on_reset_sorting_activate),
                    NULL);
  g_signal_connect ((gpointer) save_song_order1, "activate",
                    G_CALLBACK (on_save_song_order1_activate),
                    NULL);
  g_signal_connect ((gpointer) update_playlist_menu, "activate",
                    G_CALLBACK (on_update_playlist_activate),
                    NULL);
  g_signal_connect ((gpointer) update_tab_entry_menu, "activate",
                    G_CALLBACK (on_update_tab_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) update_songs_menu, "activate",
                    G_CALLBACK (on_update_songs_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_playlist_menu, "activate",
                    G_CALLBACK (on_delete_playlist_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_tab_entry_menu, "activate",
                    G_CALLBACK (on_delete_tab_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_songs_menu, "activate",
                    G_CALLBACK (on_delete_songs_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_preferences1, "activate",
                    G_CALLBACK (on_edit_preferences1_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbar_menu, "activate",
                    G_CALLBACK (on_toolbar_menu_activate),
                    NULL);
  g_signal_connect ((gpointer) more_sort_tabs, "activate",
                    G_CALLBACK (on_more_sort_tabs_activate),
                    NULL);
  g_signal_connect ((gpointer) less_sort_tabs, "activate",
                    G_CALLBACK (on_less_sort_tabs_activate),
                    NULL);
  g_signal_connect ((gpointer) arrange_sort_tabs, "activate",
                    G_CALLBACK (on_arrange_sort_tabs_activate),
                    NULL);
  g_signal_connect ((gpointer) play_playlist_menu, "activate",
                    G_CALLBACK (on_play_playlist_activate),
                    NULL);
  g_signal_connect ((gpointer) play_tab_entry_menu, "activate",
                    G_CALLBACK (on_play_tab_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) play_songs_menu, "activate",
                    G_CALLBACK (on_play_songs_activate),
                    NULL);
  g_signal_connect ((gpointer) enqueue_playlist_menu, "activate",
                    G_CALLBACK (on_enqueue_playlist_activate),
                    NULL);
  g_signal_connect ((gpointer) enqueue_tab_entry_menu, "activate",
                    G_CALLBACK (on_enqueue_tab_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) enqueue_songs_menu, "activate",
                    G_CALLBACK (on_enqueue_songs_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) import_button, "clicked",
                    G_CALLBACK (on_import_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_files_button, "clicked",
                    G_CALLBACK (on_add_files1_button),
                    NULL);
  g_signal_connect ((gpointer) add_dirs_button, "clicked",
                    G_CALLBACK (on_add_directory1_button),
                    NULL);
  g_signal_connect ((gpointer) add_PL_button, "clicked",
                    G_CALLBACK (on_add_PL_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) new_PL_button, "clicked",
                    G_CALLBACK (on_new_playlist_button),
                    NULL);
  g_signal_connect ((gpointer) export_button, "clicked",
                    G_CALLBACK (on_export_itunes1_button),
                    NULL);
  g_signal_connect ((gpointer) stop_button, "clicked",
                    G_CALLBACK (on_stop_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) gtkpod_status, "realize",
                    G_CALLBACK (on_gtkpod_status_realize),
                    NULL);
  g_signal_connect ((gpointer) space_statusbar, "realize",
                    G_CALLBACK (on_space_statusbar_realize),
                    NULL);
  g_signal_connect ((gpointer) songs_statusbar, "realize",
                    G_CALLBACK (on_songs_statusbar_realize),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtkpod, gtkpod, "gtkpod");
  GLADE_HOOKUP_OBJECT (gtkpod, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gtkpod, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem10, "menuitem10");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem10_menu, "menuitem10_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, import_itunes_mi, "import_itunes_mi");
  GLADE_HOOKUP_OBJECT (gtkpod, image897, "image897");
  GLADE_HOOKUP_OBJECT (gtkpod, add_files1, "add_files1");
  GLADE_HOOKUP_OBJECT (gtkpod, image898, "image898");
  GLADE_HOOKUP_OBJECT (gtkpod, add_directory1, "add_directory1");
  GLADE_HOOKUP_OBJECT (gtkpod, image899, "image899");
  GLADE_HOOKUP_OBJECT (gtkpod, add_playlist1, "add_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, image900, "image900");
  GLADE_HOOKUP_OBJECT (gtkpod, export_itunes1, "export_itunes1");
  GLADE_HOOKUP_OBJECT (gtkpod, image901, "image901");
  GLADE_HOOKUP_OBJECT (gtkpod, export_menu, "export_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image902, "image902");
  GLADE_HOOKUP_OBJECT (gtkpod, export_menu_menu, "export_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, export_playlist, "export_playlist");
  GLADE_HOOKUP_OBJECT (gtkpod, export_tab_entry_menu, "export_tab_entry_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, export_songs, "export_songs");
  GLADE_HOOKUP_OBJECT (gtkpod, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (gtkpod, offline_menu, "offline_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, trennlinie1, "trennlinie1");
  GLADE_HOOKUP_OBJECT (gtkpod, ipod_directories, "ipod_directories");
  GLADE_HOOKUP_OBJECT (gtkpod, image903, "image903");
  GLADE_HOOKUP_OBJECT (gtkpod, trennlinie3, "trennlinie3");
  GLADE_HOOKUP_OBJECT (gtkpod, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem11, "menuitem11");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem11_menu, "menuitem11_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, new_playlist1, "new_playlist1");
  GLADE_HOOKUP_OBJECT (gtkpod, image904, "image904");
  GLADE_HOOKUP_OBJECT (gtkpod, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize0_menu, "alphabetize0_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image905, "image905");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize0_menu_menu, "alphabetize0_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, alpha_playlists0, "alpha_playlists0");
  GLADE_HOOKUP_OBJECT (gtkpod, alpha_sort_tab0, "alpha_sort_tab0");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize1_menu, "alphabetize1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image906, "image906");
  GLADE_HOOKUP_OBJECT (gtkpod, alphabetize1_menu_menu, "alphabetize1_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, alpha_playlists1, "alpha_playlists1");
  GLADE_HOOKUP_OBJECT (gtkpod, alpha_sort_tab1, "alpha_sort_tab1");
  GLADE_HOOKUP_OBJECT (gtkpod, reset_sorting, "reset_sorting");
  GLADE_HOOKUP_OBJECT (gtkpod, image907, "image907");
  GLADE_HOOKUP_OBJECT (gtkpod, save_song_order1, "save_song_order1");
  GLADE_HOOKUP_OBJECT (gtkpod, image908, "image908");
  GLADE_HOOKUP_OBJECT (gtkpod, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (gtkpod, update_menu, "update_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image909, "image909");
  GLADE_HOOKUP_OBJECT (gtkpod, update_menu_menu, "update_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, update_playlist_menu, "update_playlist_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, update_tab_entry_menu, "update_tab_entry_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, update_songs_menu, "update_songs_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_menu, "delete_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image910, "image910");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_menu_menu, "delete_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_playlist_menu, "delete_playlist_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_tab_entry_menu, "delete_tab_entry_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, delete_songs_menu, "delete_songs_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (gtkpod, edit_preferences1, "edit_preferences1");
  GLADE_HOOKUP_OBJECT (gtkpod, image911, "image911");
  GLADE_HOOKUP_OBJECT (gtkpod, item1, "item1");
  GLADE_HOOKUP_OBJECT (gtkpod, item1_menu, "item1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, toolbar_menu, "toolbar_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, more_sort_tabs, "more_sort_tabs");
  GLADE_HOOKUP_OBJECT (gtkpod, image912, "image912");
  GLADE_HOOKUP_OBJECT (gtkpod, less_sort_tabs, "less_sort_tabs");
  GLADE_HOOKUP_OBJECT (gtkpod, image913, "image913");
  GLADE_HOOKUP_OBJECT (gtkpod, arrange_sort_tabs, "arrange_sort_tabs");
  GLADE_HOOKUP_OBJECT (gtkpod, tools1, "tools1");
  GLADE_HOOKUP_OBJECT (gtkpod, tools1_menu, "tools1_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, play_menu, "play_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image914, "image914");
  GLADE_HOOKUP_OBJECT (gtkpod, play_menu_menu, "play_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, play_playlist_menu, "play_playlist_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, play_tab_entry_menu, "play_tab_entry_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, play_songs_menu, "play_songs_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, enqueue_menu, "enqueue_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, image915, "image915");
  GLADE_HOOKUP_OBJECT (gtkpod, enqueue_menu_menu, "enqueue_menu_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, enqueue_playlist_menu, "enqueue_playlist_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, enqueue_tab_entry_menu, "enqueue_tab_entry_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, enqueue_songs_menu, "enqueue_songs_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem13, "menuitem13");
  GLADE_HOOKUP_OBJECT (gtkpod, menuitem13_menu, "menuitem13_menu");
  GLADE_HOOKUP_OBJECT (gtkpod, about1, "about1");
  GLADE_HOOKUP_OBJECT (gtkpod, image916, "image916");
  GLADE_HOOKUP_OBJECT (gtkpod, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (gtkpod, import_button, "import_button");
  GLADE_HOOKUP_OBJECT (gtkpod, add_files_button, "add_files_button");
  GLADE_HOOKUP_OBJECT (gtkpod, add_dirs_button, "add_dirs_button");
  GLADE_HOOKUP_OBJECT (gtkpod, add_PL_button, "add_PL_button");
  GLADE_HOOKUP_OBJECT (gtkpod, new_PL_button, "new_PL_button");
  GLADE_HOOKUP_OBJECT (gtkpod, export_button, "export_button");
  GLADE_HOOKUP_OBJECT (gtkpod, stop_button, "stop_button");
  GLADE_HOOKUP_OBJECT (gtkpod, paned0, "paned0");
  GLADE_HOOKUP_OBJECT (gtkpod, playlist_window, "playlist_window");
  GLADE_HOOKUP_OBJECT (gtkpod, paned1, "paned1");
  GLADE_HOOKUP_OBJECT (gtkpod, song_window, "song_window");
  GLADE_HOOKUP_OBJECT (gtkpod, paned2, "paned2");
  GLADE_HOOKUP_OBJECT (gtkpod, gtkpod_status, "gtkpod_status");
  GLADE_HOOKUP_OBJECT (gtkpod, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (gtkpod, space_statusbar, "space_statusbar");
  GLADE_HOOKUP_OBJECT (gtkpod, songs_statusbar, "songs_statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (gtkpod), accel_group);

  return gtkpod;
}

GtkWidget*
create_gtkpod_about_window (void)
{
  GtkWidget *gtkpod_about_window;
  GtkWidget *vbox2;
  GtkWidget *about_top_box;
  GtkWidget *about_label;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow2;
  GtkWidget *credits_textview;
  GtkWidget *label3;
  GtkWidget *scrolledwindow3;
  GtkWidget *translators_textview;
  GtkWidget *label4;
  GtkWidget *hbuttonbox2;
  GtkWidget *about_close;

  gtkpod_about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gtkpod_about_window, 350, 0);
  gtk_window_set_title (GTK_WINDOW (gtkpod_about_window), _("About gtkpod"));
  gtk_window_set_default_size (GTK_WINDOW (gtkpod_about_window), 450, 450);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (gtkpod_about_window), vbox2);

  about_top_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (about_top_box);
  gtk_box_pack_start (GTK_BOX (vbox2), about_top_box, FALSE, FALSE, 0);

  about_label = gtk_label_new ("");
  gtk_widget_show (about_label);
  gtk_box_pack_start (GTK_BOX (about_top_box), about_label, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (about_label), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox2), notebook1, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  credits_textview = gtk_text_view_new ();
  gtk_widget_show (credits_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), credits_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (credits_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (credits_textview), GTK_WRAP_WORD);

  label3 = gtk_label_new (_("Credits"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  translators_textview = gtk_text_view_new ();
  gtk_widget_show (translators_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), translators_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (translators_textview), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (translators_textview), GTK_WRAP_WORD);

  label4 = gtk_label_new (_("Translators"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, FALSE, FALSE, 0);

  about_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (about_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), about_close);
  GTK_WIDGET_SET_FLAGS (about_close, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) gtkpod_about_window, "delete_event",
                            G_CALLBACK (on_about_window_close),
                            GTK_OBJECT (gtkpod_about_window));
  g_signal_connect_swapped ((gpointer) about_close, "clicked",
                            G_CALLBACK (on_about_window_close_button),
                            GTK_OBJECT (gtkpod_about_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtkpod_about_window, gtkpod_about_window, "gtkpod_about_window");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_top_box, "about_top_box");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_label, "about_label");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, credits_textview, "credits_textview");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, translators_textview, "translators_textview");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (gtkpod_about_window, about_close, "about_close");

  return gtkpod_about_window;
}

GtkWidget*
create_confirm_window (void)
{
  GtkWidget *confirm_window;
  GtkWidget *vbox6;
  GtkWidget *label;
  GtkWidget *vbox7;
  GtkWidget *scroller;
  GtkWidget *text;
  GtkWidget *hbox3;
  GtkWidget *never_again;
  GtkWidget *hbuttonbox4;
  GtkWidget *ok;
  GtkWidget *apply;
  GtkWidget *cancel;

  confirm_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (confirm_window), 6);
  gtk_window_set_title (GTK_WINDOW (confirm_window), _("window1"));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (confirm_window), vbox6);

  label = gtk_label_new (_("label21"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (vbox6), label, FALSE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label), 0.5, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  scroller = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scroller);
  gtk_box_pack_start (GTK_BOX (vbox7), scroller, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scroller), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scroller), GTK_SHADOW_IN);

  text = gtk_text_view_new ();
  gtk_widget_show (text);
  gtk_container_add (GTK_CONTAINER (scroller), text);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox3, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 2);

  never_again = gtk_check_button_new_with_mnemonic (_("Never ask this Again"));
  gtk_widget_show (never_again);
  gtk_box_pack_start (GTK_BOX (hbox3), never_again, FALSE, FALSE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox4, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox4), 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_SPREAD);

  ok = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), ok);
  GTK_WIDGET_SET_FLAGS (ok, GTK_CAN_DEFAULT);

  apply = gtk_button_new_with_mnemonic (_("Apply"));
  gtk_widget_show (apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), apply);
  GTK_WIDGET_SET_FLAGS (apply, GTK_CAN_DEFAULT);

  cancel = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), cancel);
  GTK_WIDGET_SET_FLAGS (cancel, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirm_window, confirm_window, "confirm_window");
  GLADE_HOOKUP_OBJECT (confirm_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (confirm_window, label, "label");
  GLADE_HOOKUP_OBJECT (confirm_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (confirm_window, scroller, "scroller");
  GLADE_HOOKUP_OBJECT (confirm_window, text, "text");
  GLADE_HOOKUP_OBJECT (confirm_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (confirm_window, never_again, "never_again");
  GLADE_HOOKUP_OBJECT (confirm_window, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (confirm_window, ok, "ok");
  GLADE_HOOKUP_OBJECT (confirm_window, apply, "apply");
  GLADE_HOOKUP_OBJECT (confirm_window, cancel, "cancel");

  return confirm_window;
}

GtkWidget*
create_new_prefs_window (void)
{
  GtkWidget *new_prefs_window;
  GtkWidget *vbox13;
  GtkWidget *notebook;
  GtkWidget *vbox14;
  GtkWidget *frame6;
  GtkWidget *vbox15;
  GtkWidget *hbox8;
  GtkWidget *label27;
  GtkWidget *cfg_mount_point;
  GtkWidget *cfg_autoimport;
  GtkWidget *label26;
  GtkWidget *frame7;
  GtkWidget *vbox16;
  GtkWidget *hbox9;
  GtkWidget *label29;
  GtkWidget *charset_combo;
  GtkWidget *charset_combo_entry;
  GtkWidget *cfg_md5songs;
  GtkWidget *table2;
  GtkWidget *cfg_show_duplicates;
  GtkWidget *cfg_update_existing;
  GtkWidget *table1;
  GtkWidget *cfg_show_updated;
  GtkWidget *cfg_show_non_updated;
  GtkWidget *label28;
  GtkWidget *frame8;
  GtkWidget *hbox10;
  GtkWidget *vbox17;
  GtkWidget *tag_autoset1;
  GtkWidget *tag_autoset3;
  GtkWidget *vbox18;
  GtkWidget *tag_autoset2;
  GtkWidget *tag_autoset4;
  GtkWidget *vbox19;
  GtkWidget *tag_autoset0;
  GtkWidget *label30;
  GtkWidget *label23;
  GtkWidget *vbox20;
  GtkWidget *frame9;
  GtkWidget *vbox21;
  GtkWidget *cfg_write_extended;
  GtkWidget *cfg_keep_backups;
  GtkWidget *label31;
  GtkWidget *frame10;
  GtkWidget *vbox22;
  GtkWidget *cfg_id3_write;
  GtkWidget *table3;
  GtkWidget *cfg_id3_writeall;
  GtkWidget *label32;
  GtkWidget *label24;
  GtkWidget *vbox23;
  GtkWidget *frame16;
  GtkWidget *vbox31;
  GtkWidget *cfg_display_toolbar;
  GtkWidget *table4;
  GtkWidget *cfg_toolbar_style_both;
  GSList *cfg_toolbar_style_both_group = NULL;
  GtkWidget *cfg_toolbar_style_text;
  GtkWidget *cfg_toolbar_style_icons;
  GtkWidget *label39;
  GtkWidget *frame12;
  GtkWidget *vbox25;
  GtkWidget *hbox11;
  GtkWidget *label35;
  GtkWidget *sort_tab_num_combo;
  GtkWidget *sort_tab_num_combo_entry;
  GtkWidget *label34;
  GtkWidget *frame13;
  GtkWidget *autoselect_vbox;
  GtkWidget *cfg_mpl_autoselect;
  GtkWidget *label40;
  GtkWidget *autoselect_hbox;
  GtkWidget *label36;
  GtkWidget *frame14;
  GtkWidget *hbox12;
  GtkWidget *vbox27;
  GtkWidget *col_visible1;
  GtkWidget *col_visible3;
  GtkWidget *col_visible6;
  GtkWidget *col_visible9;
  GtkWidget *vbox28;
  GtkWidget *col_visible2;
  GtkWidget *col_visible4;
  GtkWidget *col_visible7;
  GtkWidget *col_visible10;
  GtkWidget *vbox29;
  GtkWidget *col_visible0;
  GtkWidget *col_visible5;
  GtkWidget *col_visible8;
  GtkWidget *label37;
  GtkWidget *frame15;
  GtkWidget *vbox30;
  GtkWidget *cfg_block_display;
  GtkWidget *label38;
  GtkWidget *label25;
  GtkWidget *vbox32;
  GtkWidget *frame18;
  GtkWidget *vbox34;
  GtkWidget *label44;
  GtkWidget *play_now_path_entry;
  GtkWidget *label45;
  GtkWidget *play_enqueue_path_entry;
  GtkWidget *label43;
  GtkWidget *frame11;
  GtkWidget *vbox24;
  GtkWidget *cfg_delete_playlist;
  GtkWidget *cfg_delete_track_from_playlist;
  GtkWidget *cfg_delete_track_from_ipod;
  GtkWidget *label33;
  GtkWidget *frame17;
  GtkWidget *vbox33;
  GtkWidget *cfg_save_sorted_order;
  GtkWidget *cfg_automount_ipod;
  GtkWidget *label42;
  GtkWidget *label41;
  GtkWidget *hbuttonbox5;
  GtkWidget *prefs_apply;
  GtkWidget *prefs_cancel;
  GtkWidget *prefs_ok;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  new_prefs_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (new_prefs_window), _("Preferences"));

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (new_prefs_window), vbox13);

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox13), notebook, TRUE, TRUE, 0);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_container_add (GTK_CONTAINER (notebook), vbox14);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox14), frame6, TRUE, TRUE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_container_add (GTK_CONTAINER (frame6), vbox15);

  hbox8 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox15), hbox8, FALSE, FALSE, 0);

  label27 = gtk_label_new (_(" iPod Mount Point:"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_LEFT);

  cfg_mount_point = gtk_entry_new ();
  gtk_widget_show (cfg_mount_point);
  gtk_box_pack_start (GTK_BOX (hbox8), cfg_mount_point, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_mount_point, _("Where you mounted your iPod's filesystem. Usually '/mnt/ipod/' or similar."), NULL);

  cfg_autoimport = gtk_check_button_new_with_mnemonic (_("Automatically import iTunesDB on startup"));
  gtk_widget_show (cfg_autoimport);
  gtk_box_pack_start (GTK_BOX (vbox15), cfg_autoimport, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("iTunesDB"));
  gtk_widget_show (label26);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label26);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_LEFT);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox14), frame7, TRUE, TRUE, 0);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_container_add (GTK_CONTAINER (frame7), vbox16);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox9, FALSE, FALSE, 0);

  label29 = gtk_label_new (_(" Charset (ID3, files): "));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox9), label29, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label29), GTK_JUSTIFY_LEFT);

  charset_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (charset_combo)->popwin),
                     "GladeParentKey", charset_combo);
  gtk_widget_show (charset_combo);
  gtk_box_pack_start (GTK_BOX (hbox9), charset_combo, TRUE, TRUE, 0);

  charset_combo_entry = GTK_COMBO (charset_combo)->entry;
  gtk_widget_show (charset_combo_entry);
  gtk_tooltips_set_tip (tooltips, charset_combo_entry, _("gtkpod expects the ID3 tags and the filenames to be in the encoding specified here. You can change it for consecutive 'Add Files' and 'Add Dirs' operation. 'System Charset' is the charset used by your current locale."), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (charset_combo_entry), FALSE);

  cfg_md5songs = gtk_check_button_new_with_mnemonic (_("Don't allow file duplication"));
  gtk_widget_show (cfg_md5songs);
  gtk_box_pack_start (GTK_BOX (vbox16), cfg_md5songs, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_md5songs, _("Duplicate Recognition is based on a md5 hash over the file."), NULL);

  table2 = gtk_table_new (1, 1, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox16), table2, FALSE, FALSE, 0);

  cfg_show_duplicates = gtk_check_button_new_with_mnemonic (_("Display info about detected duplicates"));
  gtk_widget_show (cfg_show_duplicates);
  gtk_table_attach (GTK_TABLE (table2), cfg_show_duplicates, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_tooltips_set_tip (tooltips, cfg_show_duplicates, _("Display the list of duplicates that have been detected after adding files."), NULL);

  cfg_update_existing = gtk_check_button_new_with_mnemonic (_("When adding dirs/files, update information of\nexisting songs with identical filenames"));
  gtk_widget_show (cfg_update_existing);
  gtk_box_pack_start (GTK_BOX (vbox16), cfg_update_existing, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_update_existing, _("If the filename (full path) of an existing song matches that of a song to be added, this option allows you to update the information of the existing song rather than adding the song again. Please note that this option is different from the option above: duplicates are completely identical, having the same filename still allows for different ID3 tags. On export the updated song is copied to the iPod overwriting the old version."), NULL);

  table1 = gtk_table_new (2, 1, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox16), table1, FALSE, FALSE, 0);

  cfg_show_updated = gtk_check_button_new_with_mnemonic (_("Display info about updated songs"));
  gtk_widget_show (cfg_show_updated);
  gtk_table_attach (GTK_TABLE (table1), cfg_show_updated, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_tooltips_set_tip (tooltips, cfg_show_updated, _("Display a list of songs that could actually be updated."), NULL);

  cfg_show_non_updated = gtk_check_button_new_with_mnemonic (_("Display info about non-updated songs"));
  gtk_widget_show (cfg_show_non_updated);
  gtk_table_attach (GTK_TABLE (table1), cfg_show_non_updated, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_tooltips_set_tip (tooltips, cfg_show_non_updated, _("Display a list of songs that could not be updated."), NULL);

  label28 = gtk_label_new (_("Adding Songs"));
  gtk_widget_show (label28);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label28);
  gtk_label_set_justify (GTK_LABEL (label28), GTK_JUSTIFY_LEFT);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox14), frame8, TRUE, TRUE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (frame8), hbox10);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox17, TRUE, TRUE, 0);

  tag_autoset1 = gtk_check_button_new_with_mnemonic (_("Artist"));
  gtk_widget_show (tag_autoset1);
  gtk_box_pack_start (GTK_BOX (vbox17), tag_autoset1, FALSE, FALSE, 0);

  tag_autoset3 = gtk_check_button_new_with_mnemonic (_("Genre"));
  gtk_widget_show (tag_autoset3);
  gtk_box_pack_start (GTK_BOX (vbox17), tag_autoset3, FALSE, FALSE, 0);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox18);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox18, TRUE, TRUE, 0);

  tag_autoset2 = gtk_check_button_new_with_mnemonic (_("Album"));
  gtk_widget_show (tag_autoset2);
  gtk_box_pack_start (GTK_BOX (vbox18), tag_autoset2, FALSE, FALSE, 0);

  tag_autoset4 = gtk_check_button_new_with_mnemonic (_("Composer"));
  gtk_widget_show (tag_autoset4);
  gtk_box_pack_start (GTK_BOX (vbox18), tag_autoset4, FALSE, FALSE, 0);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox19, TRUE, TRUE, 0);

  tag_autoset0 = gtk_check_button_new_with_mnemonic (_("Title"));
  gtk_widget_show (tag_autoset0);
  gtk_box_pack_start (GTK_BOX (vbox19), tag_autoset0, FALSE, FALSE, 0);

  label30 = gtk_label_new (_("Automatically Set Empty ID3-Tags To Filename?"));
  gtk_widget_show (label30);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label30);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_LEFT);

  label23 = gtk_label_new (_("Import"));
  gtk_widget_show (label23);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label23);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);

  vbox20 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox20);
  gtk_container_add (GTK_CONTAINER (notebook), vbox20);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_box_pack_start (GTK_BOX (vbox20), frame9, TRUE, TRUE, 0);

  vbox21 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox21);
  gtk_container_add (GTK_CONTAINER (frame9), vbox21);

  cfg_write_extended = gtk_check_button_new_with_mnemonic (_("Write extended information (PC filenames,\nMD5 hashes). Recommended."));
  gtk_widget_show (cfg_write_extended);
  gtk_box_pack_start (GTK_BOX (vbox21), cfg_write_extended, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_write_extended, _("Highly recommended for faster import when taking advantage of the duplication recognition. Also, having the PC filenames allows writing changed ID3 tags to disk, and even to reconstruct your ipod's contents in case of file system corruption (change the \"transferred=\" entries in your backuped database)."), NULL);

  cfg_keep_backups = gtk_check_button_new_with_mnemonic (_("Keep a backup of the iTunesDB in ~/.gtkpod/"));
  gtk_widget_show (cfg_keep_backups);
  gtk_box_pack_start (GTK_BOX (vbox21), cfg_keep_backups, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("iTunesDB"));
  gtk_widget_show (label31);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label31);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_LEFT);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_show (frame10);
  gtk_box_pack_start (GTK_BOX (vbox20), frame10, TRUE, TRUE, 0);

  vbox22 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox22);
  gtk_container_add (GTK_CONTAINER (frame10), vbox22);

  cfg_id3_write = gtk_check_button_new_with_mnemonic (_("Write ID3 tags to disk when modified in gtkpod"));
  gtk_widget_show (cfg_id3_write);
  gtk_box_pack_start (GTK_BOX (vbox22), cfg_id3_write, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_id3_write, _("The tags are written to the files on your harddrive and on the ipod (if available)."), NULL);

  table3 = gtk_table_new (1, 1, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox22), table3, FALSE, FALSE, 0);

  cfg_id3_writeall = gtk_check_button_new_with_mnemonic (_("Update all tags (not only changed ones)"));
  gtk_widget_show (cfg_id3_writeall);
  gtk_table_attach (GTK_TABLE (table3), cfg_id3_writeall, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_tooltips_set_tip (tooltips, cfg_id3_writeall, _("Normally only the tag you changed is written to disk."), NULL);

  label32 = gtk_label_new (_("Songs"));
  gtk_widget_show (label32);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), label32);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);

  label24 = gtk_label_new (_("Export"));
  gtk_widget_show (label24);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label24);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);

  vbox23 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox23);
  gtk_container_add (GTK_CONTAINER (notebook), vbox23);

  frame16 = gtk_frame_new (NULL);
  gtk_widget_show (frame16);
  gtk_box_pack_start (GTK_BOX (vbox23), frame16, TRUE, TRUE, 0);

  vbox31 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox31);
  gtk_container_add (GTK_CONTAINER (frame16), vbox31);

  cfg_display_toolbar = gtk_check_button_new_with_mnemonic (_("Display toolbar..."));
  gtk_widget_show (cfg_display_toolbar);
  gtk_box_pack_start (GTK_BOX (vbox31), cfg_display_toolbar, FALSE, FALSE, 0);

  table4 = gtk_table_new (3, 1, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox31), table4, FALSE, FALSE, 0);

  cfg_toolbar_style_both = gtk_radio_button_new_with_mnemonic (NULL, _("...both as icons and text"));
  gtk_widget_show (cfg_toolbar_style_both);
  gtk_table_attach (GTK_TABLE (table4), cfg_toolbar_style_both, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (cfg_toolbar_style_both), cfg_toolbar_style_both_group);
  cfg_toolbar_style_both_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (cfg_toolbar_style_both));

  cfg_toolbar_style_text = gtk_radio_button_new_with_mnemonic (NULL, _("...as text"));
  gtk_widget_show (cfg_toolbar_style_text);
  gtk_table_attach (GTK_TABLE (table4), cfg_toolbar_style_text, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (cfg_toolbar_style_text), cfg_toolbar_style_both_group);
  cfg_toolbar_style_both_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (cfg_toolbar_style_text));

  cfg_toolbar_style_icons = gtk_radio_button_new_with_mnemonic (NULL, _("...as icons"));
  gtk_widget_show (cfg_toolbar_style_icons);
  gtk_table_attach (GTK_TABLE (table4), cfg_toolbar_style_icons, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 20, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (cfg_toolbar_style_icons), cfg_toolbar_style_both_group);
  cfg_toolbar_style_both_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (cfg_toolbar_style_icons));

  label39 = gtk_label_new (_("Toolbar"));
  gtk_widget_show (label39);
  gtk_frame_set_label_widget (GTK_FRAME (frame16), label39);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_LEFT);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_show (frame12);
  gtk_box_pack_start (GTK_BOX (vbox23), frame12, TRUE, TRUE, 0);

  vbox25 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox25);
  gtk_container_add (GTK_CONTAINER (frame12), vbox25);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox25), hbox11, FALSE, FALSE, 0);

  label35 = gtk_label_new (_(" Number of sort tabs: "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox11), label35, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_LEFT);

  sort_tab_num_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (sort_tab_num_combo)->popwin),
                     "GladeParentKey", sort_tab_num_combo);
  gtk_widget_show (sort_tab_num_combo);
  gtk_box_pack_start (GTK_BOX (hbox11), sort_tab_num_combo, TRUE, TRUE, 0);

  sort_tab_num_combo_entry = GTK_COMBO (sort_tab_num_combo)->entry;
  gtk_widget_show (sort_tab_num_combo_entry);
  gtk_editable_set_editable (GTK_EDITABLE (sort_tab_num_combo_entry), FALSE);

  label34 = gtk_label_new (_("Sort Tabs"));
  gtk_widget_show (label34);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), label34);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_LEFT);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_show (frame13);
  gtk_box_pack_start (GTK_BOX (vbox23), frame13, FALSE, TRUE, 0);

  autoselect_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (autoselect_vbox);
  gtk_container_add (GTK_CONTAINER (frame13), autoselect_vbox);

  cfg_mpl_autoselect = gtk_check_button_new_with_mnemonic (_("...master playlist"));
  gtk_widget_show (cfg_mpl_autoselect);
  gtk_box_pack_start (GTK_BOX (autoselect_vbox), cfg_mpl_autoselect, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_mpl_autoselect, _("If you don't select the master playlist automatically, the initial database import is much faster because the display dosn't have to be updated."), NULL);

  label40 = gtk_label_new (_("...entry 'All' in sort tab..."));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (autoselect_vbox), label40, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label40), 20, 0);

  autoselect_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (autoselect_hbox);
  gtk_box_pack_start (GTK_BOX (autoselect_vbox), autoselect_hbox, TRUE, TRUE, 0);

  label36 = gtk_label_new (_("Automatically select..."));
  gtk_widget_show (label36);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label36);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_LEFT);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_show (frame14);
  gtk_box_pack_start (GTK_BOX (vbox23), frame14, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (frame14), hbox12);

  vbox27 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox27);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox27, TRUE, TRUE, 0);

  col_visible1 = gtk_check_button_new_with_mnemonic (_("Artist"));
  gtk_widget_show (col_visible1);
  gtk_box_pack_start (GTK_BOX (vbox27), col_visible1, FALSE, FALSE, 0);

  col_visible3 = gtk_check_button_new_with_mnemonic (_("Genre"));
  gtk_widget_show (col_visible3);
  gtk_box_pack_start (GTK_BOX (vbox27), col_visible3, FALSE, FALSE, 0);

  col_visible6 = gtk_check_button_new_with_mnemonic (_("iPod ID"));
  gtk_widget_show (col_visible6);
  gtk_box_pack_start (GTK_BOX (vbox27), col_visible6, FALSE, FALSE, 0);

  col_visible9 = gtk_check_button_new_with_mnemonic (_("File Size"));
  gtk_widget_show (col_visible9);
  gtk_box_pack_start (GTK_BOX (vbox27), col_visible9, FALSE, FALSE, 0);

  vbox28 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox28);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox28, TRUE, TRUE, 0);

  col_visible2 = gtk_check_button_new_with_mnemonic (_("Album"));
  gtk_widget_show (col_visible2);
  gtk_box_pack_start (GTK_BOX (vbox28), col_visible2, FALSE, FALSE, 0);

  col_visible4 = gtk_check_button_new_with_mnemonic (_("Composer"));
  gtk_widget_show (col_visible4);
  gtk_box_pack_start (GTK_BOX (vbox28), col_visible4, FALSE, FALSE, 0);

  col_visible7 = gtk_check_button_new_with_mnemonic (_("PC File"));
  gtk_widget_show (col_visible7);
  gtk_box_pack_start (GTK_BOX (vbox28), col_visible7, FALSE, FALSE, 0);

  col_visible10 = gtk_check_button_new_with_mnemonic (_("Play Time"));
  gtk_widget_show (col_visible10);
  gtk_box_pack_start (GTK_BOX (vbox28), col_visible10, FALSE, FALSE, 0);

  vbox29 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox29);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox29, TRUE, TRUE, 0);

  col_visible0 = gtk_check_button_new_with_mnemonic (_("Title"));
  gtk_widget_show (col_visible0);
  gtk_box_pack_start (GTK_BOX (vbox29), col_visible0, FALSE, FALSE, 0);

  col_visible5 = gtk_check_button_new_with_mnemonic (_("Track Number (#)"));
  gtk_widget_show (col_visible5);
  gtk_box_pack_start (GTK_BOX (vbox29), col_visible5, FALSE, FALSE, 0);

  col_visible8 = gtk_check_button_new_with_mnemonic (_("Transferred"));
  gtk_widget_show (col_visible8);
  gtk_box_pack_start (GTK_BOX (vbox29), col_visible8, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("Displayed Song Attributes "));
  gtk_widget_show (label37);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label37);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_LEFT);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_show (frame15);
  gtk_box_pack_start (GTK_BOX (vbox23), frame15, TRUE, TRUE, 0);

  vbox30 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox30);
  gtk_container_add (GTK_CONTAINER (frame15), vbox30);

  cfg_block_display = gtk_check_button_new_with_mnemonic (_("Block display when changing playlist or tab\nentry (faster!)"));
  gtk_widget_show (cfg_block_display);
  gtk_box_pack_start (GTK_BOX (vbox30), cfg_block_display, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_block_display, _("The display can be blocked after changing a selection. The display update is faster, but you have to wait until it's finished."), NULL);

  label38 = gtk_label_new (_("Misc"));
  gtk_widget_show (label38);
  gtk_frame_set_label_widget (GTK_FRAME (frame15), label38);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_LEFT);

  label25 = gtk_label_new (_("Display"));
  gtk_widget_show (label25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label25);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);

  vbox32 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox32);
  gtk_container_add (GTK_CONTAINER (notebook), vbox32);

  frame18 = gtk_frame_new (NULL);
  gtk_widget_show (frame18);
  gtk_box_pack_start (GTK_BOX (vbox32), frame18, TRUE, TRUE, 0);

  vbox34 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox34);
  gtk_container_add (GTK_CONTAINER (frame18), vbox34);

  label44 = gtk_label_new (_("Command Line for 'Play Now':"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (vbox34), label44, FALSE, FALSE, 2);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label44), 0.01, 0.5);

  play_now_path_entry = gtk_entry_new ();
  gtk_widget_show (play_now_path_entry);
  gtk_box_pack_start (GTK_BOX (vbox34), play_now_path_entry, FALSE, FALSE, 2);
  gtk_tooltips_set_tip (tooltips, play_now_path_entry, _("For example, 'xmms -p %s' will clear xmms' current playlist, add the selected songs and start playing."), NULL);

  label45 = gtk_label_new (_("Command Line for 'Enqueue'"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (vbox34), label45, FALSE, FALSE, 4);
  gtk_label_set_justify (GTK_LABEL (label45), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label45), 0.01, 0.5);

  play_enqueue_path_entry = gtk_entry_new ();
  gtk_widget_show (play_enqueue_path_entry);
  gtk_box_pack_start (GTK_BOX (vbox34), play_enqueue_path_entry, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, play_enqueue_path_entry, _("For example, 'xmms -e %s' will append (enqueue) the selected songs to xmms' current playlist."), NULL);

  label43 = gtk_label_new (_("Song Playing"));
  gtk_widget_show (label43);
  gtk_frame_set_label_widget (GTK_FRAME (frame18), label43);
  gtk_label_set_justify (GTK_LABEL (label43), GTK_JUSTIFY_LEFT);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_show (frame11);
  gtk_box_pack_start (GTK_BOX (vbox32), frame11, TRUE, TRUE, 0);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox24);
  gtk_container_add (GTK_CONTAINER (frame11), vbox24);

  cfg_delete_playlist = gtk_check_button_new_with_mnemonic (_("Before removing playlists"));
  gtk_widget_show (cfg_delete_playlist);
  gtk_box_pack_start (GTK_BOX (vbox24), cfg_delete_playlist, FALSE, FALSE, 0);

  cfg_delete_track_from_playlist = gtk_check_button_new_with_mnemonic (_("Before removing tracks from playlist"));
  gtk_widget_show (cfg_delete_track_from_playlist);
  gtk_box_pack_start (GTK_BOX (vbox24), cfg_delete_track_from_playlist, FALSE, FALSE, 0);

  cfg_delete_track_from_ipod = gtk_check_button_new_with_mnemonic (_("Before removing tracks completely from iPod"));
  gtk_widget_show (cfg_delete_track_from_ipod);
  gtk_box_pack_start (GTK_BOX (vbox24), cfg_delete_track_from_ipod, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("Delete Confirmation "));
  gtk_widget_show (label33);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label33);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_LEFT);

  frame17 = gtk_frame_new (NULL);
  gtk_widget_show (frame17);
  gtk_box_pack_start (GTK_BOX (vbox32), frame17, TRUE, TRUE, 0);

  vbox33 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox33);
  gtk_container_add (GTK_CONTAINER (frame17), vbox33);

  cfg_save_sorted_order = gtk_check_button_new_with_mnemonic (_("Automatically save song order after sorting."));
  gtk_widget_show (cfg_save_sorted_order);
  gtk_box_pack_start (GTK_BOX (vbox33), cfg_save_sorted_order, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_save_sorted_order, _("Alternatively you can use the menu item 'Save Displayed Song Order' to save the sort order."), NULL);

  cfg_automount_ipod = gtk_check_button_new_with_mnemonic (_("Handle mounting/unmounting of iPod drive"));
  gtk_widget_show (cfg_automount_ipod);
  gtk_box_pack_start (GTK_BOX (vbox33), cfg_automount_ipod, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cfg_automount_ipod, _("On startup gtkpod will call 'mount <ipod mountpoint>', on exit a 'umount <ipod mountpoint>' call is carried out. For more complicated arrangements please use the ~/.gtkpod/gtkpod.in and ~/.gtkpod/gtkpod.out scripts."), NULL);

  label42 = gtk_label_new (_("Misc"));
  gtk_widget_show (label42);
  gtk_frame_set_label_widget (GTK_FRAME (frame17), label42);
  gtk_label_set_justify (GTK_LABEL (label42), GTK_JUSTIFY_LEFT);

  label41 = gtk_label_new (_("Misc"));
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 3), label41);
  gtk_label_set_justify (GTK_LABEL (label41), GTK_JUSTIFY_LEFT);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox13), hbuttonbox5, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_SPREAD);

  prefs_apply = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (prefs_apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), prefs_apply);
  GTK_WIDGET_SET_FLAGS (prefs_apply, GTK_CAN_DEFAULT);

  prefs_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (prefs_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), prefs_cancel);
  GTK_WIDGET_SET_FLAGS (prefs_cancel, GTK_CAN_DEFAULT);

  prefs_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (prefs_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), prefs_ok);
  GTK_WIDGET_SET_FLAGS (prefs_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) new_prefs_window, "delete_event",
                    G_CALLBACK (on_prefs_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) cfg_mount_point, "changed",
                    G_CALLBACK (on_cfg_mount_point_changed),
                    NULL);
  g_signal_connect ((gpointer) cfg_autoimport, "toggled",
                    G_CALLBACK (on_cfg_autoimport_toggled),
                    NULL);
  g_signal_connect ((gpointer) charset_combo_entry, "changed",
                    G_CALLBACK (on_charset_combo_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) cfg_md5songs, "toggled",
                    G_CALLBACK (on_cfg_md5songs_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_show_duplicates, "toggled",
                    G_CALLBACK (on_cfg_show_duplicates_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_update_existing, "toggled",
                    G_CALLBACK (on_cfg_update_existing_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_show_updated, "toggled",
                    G_CALLBACK (on_cfg_show_updated_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_show_non_updated, "toggled",
                    G_CALLBACK (on_cfg_show_non_updated_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_write_extended, "toggled",
                    G_CALLBACK (on_cfg_write_extended_info_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_keep_backups, "toggled",
                    G_CALLBACK (on_cfg_keep_backups_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_id3_write, "toggled",
                    G_CALLBACK (on_cfg_id3_write_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_id3_writeall, "toggled",
                    G_CALLBACK (on_cfg_id3_writeall_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_display_toolbar, "toggled",
                    G_CALLBACK (on_cfg_display_toolbar_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_toolbar_style_both, "toggled",
                    G_CALLBACK (on_cfg_toolbar_style_both_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_toolbar_style_text, "toggled",
                    G_CALLBACK (on_cfg_toolbar_style_text_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_toolbar_style_icons, "toggled",
                    G_CALLBACK (on_cfg_toolbar_style_icons_toggled),
                    NULL);
  g_signal_connect ((gpointer) sort_tab_num_combo_entry, "changed",
                    G_CALLBACK (on_sort_tab_num_combo_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) cfg_mpl_autoselect, "toggled",
                    G_CALLBACK (on_cfg_mpl_autoselect_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_block_display, "toggled",
                    G_CALLBACK (on_cfg_block_display_toggled),
                    NULL);
  g_signal_connect ((gpointer) play_now_path_entry, "changed",
                    G_CALLBACK (on_play_now_path_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) play_enqueue_path_entry, "changed",
                    G_CALLBACK (on_play_enqueue_path_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_playlist, "toggled",
                    G_CALLBACK (on_cfg_delete_playlist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_track_from_playlist, "toggled",
                    G_CALLBACK (on_cfg_delete_track_from_playlist_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_delete_track_from_ipod, "toggled",
                    G_CALLBACK (on_cfg_delete_track_from_ipod_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_save_sorted_order, "toggled",
                    G_CALLBACK (on_cfg_save_sorted_order_toggled),
                    NULL);
  g_signal_connect ((gpointer) cfg_automount_ipod, "toggled",
                    G_CALLBACK (on_cfg_automount_ipod_toggled),
                    NULL);
  g_signal_connect ((gpointer) prefs_apply, "clicked",
                    G_CALLBACK (on_prefs_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) prefs_cancel, "clicked",
                    G_CALLBACK (on_prefs_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) prefs_ok, "clicked",
                    G_CALLBACK (on_prefs_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (new_prefs_window, new_prefs_window, "new_prefs_window");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (new_prefs_window, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (new_prefs_window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label27, "label27");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_mount_point, "cfg_mount_point");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_autoimport, "cfg_autoimport");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label26, "label26");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (new_prefs_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label29, "label29");
  GLADE_HOOKUP_OBJECT (new_prefs_window, charset_combo, "charset_combo");
  GLADE_HOOKUP_OBJECT (new_prefs_window, charset_combo_entry, "charset_combo_entry");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_md5songs, "cfg_md5songs");
  GLADE_HOOKUP_OBJECT (new_prefs_window, table2, "table2");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_show_duplicates, "cfg_show_duplicates");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_update_existing, "cfg_update_existing");
  GLADE_HOOKUP_OBJECT (new_prefs_window, table1, "table1");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_show_updated, "cfg_show_updated");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_show_non_updated, "cfg_show_non_updated");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label28, "label28");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (new_prefs_window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (new_prefs_window, tag_autoset1, "tag_autoset1");
  GLADE_HOOKUP_OBJECT (new_prefs_window, tag_autoset3, "tag_autoset3");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (new_prefs_window, tag_autoset2, "tag_autoset2");
  GLADE_HOOKUP_OBJECT (new_prefs_window, tag_autoset4, "tag_autoset4");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (new_prefs_window, tag_autoset0, "tag_autoset0");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label30, "label30");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label23, "label23");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox20, "vbox20");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox21, "vbox21");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_write_extended, "cfg_write_extended");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_keep_backups, "cfg_keep_backups");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label31, "label31");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox22, "vbox22");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_id3_write, "cfg_id3_write");
  GLADE_HOOKUP_OBJECT (new_prefs_window, table3, "table3");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_id3_writeall, "cfg_id3_writeall");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label32, "label32");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label24, "label24");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame16, "frame16");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox31, "vbox31");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_display_toolbar, "cfg_display_toolbar");
  GLADE_HOOKUP_OBJECT (new_prefs_window, table4, "table4");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_toolbar_style_both, "cfg_toolbar_style_both");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_toolbar_style_text, "cfg_toolbar_style_text");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_toolbar_style_icons, "cfg_toolbar_style_icons");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label39, "label39");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (new_prefs_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label35, "label35");
  GLADE_HOOKUP_OBJECT (new_prefs_window, sort_tab_num_combo, "sort_tab_num_combo");
  GLADE_HOOKUP_OBJECT (new_prefs_window, sort_tab_num_combo_entry, "sort_tab_num_combo_entry");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label34, "label34");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (new_prefs_window, autoselect_vbox, "autoselect_vbox");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_mpl_autoselect, "cfg_mpl_autoselect");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label40, "label40");
  GLADE_HOOKUP_OBJECT (new_prefs_window, autoselect_hbox, "autoselect_hbox");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label36, "label36");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (new_prefs_window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox27, "vbox27");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible1, "col_visible1");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible3, "col_visible3");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible6, "col_visible6");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible9, "col_visible9");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox28, "vbox28");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible2, "col_visible2");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible4, "col_visible4");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible7, "col_visible7");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible10, "col_visible10");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox29, "vbox29");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible0, "col_visible0");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible5, "col_visible5");
  GLADE_HOOKUP_OBJECT (new_prefs_window, col_visible8, "col_visible8");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label37, "label37");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame15, "frame15");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox30, "vbox30");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_block_display, "cfg_block_display");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label38, "label38");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label25, "label25");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox32, "vbox32");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame18, "frame18");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox34, "vbox34");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label44, "label44");
  GLADE_HOOKUP_OBJECT (new_prefs_window, play_now_path_entry, "play_now_path_entry");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label45, "label45");
  GLADE_HOOKUP_OBJECT (new_prefs_window, play_enqueue_path_entry, "play_enqueue_path_entry");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label43, "label43");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_delete_playlist, "cfg_delete_playlist");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_delete_track_from_playlist, "cfg_delete_track_from_playlist");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_delete_track_from_ipod, "cfg_delete_track_from_ipod");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label33, "label33");
  GLADE_HOOKUP_OBJECT (new_prefs_window, frame17, "frame17");
  GLADE_HOOKUP_OBJECT (new_prefs_window, vbox33, "vbox33");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_save_sorted_order, "cfg_save_sorted_order");
  GLADE_HOOKUP_OBJECT (new_prefs_window, cfg_automount_ipod, "cfg_automount_ipod");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label42, "label42");
  GLADE_HOOKUP_OBJECT (new_prefs_window, label41, "label41");
  GLADE_HOOKUP_OBJECT (new_prefs_window, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (new_prefs_window, prefs_apply, "prefs_apply");
  GLADE_HOOKUP_OBJECT (new_prefs_window, prefs_cancel, "prefs_cancel");
  GLADE_HOOKUP_OBJECT (new_prefs_window, prefs_ok, "prefs_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (new_prefs_window, tooltips, "tooltips");

  return new_prefs_window;
}

