/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gtkpod (void);
GtkWidget* create_gtkpod_about_window (void);
GtkWidget* create_confirm_window (void);
GtkWidget* create_prefs_window (void);
GtkWidget* create_special_sorttab (void);
GtkWidget* create_calendar_window (void);
GtkWidget* create_sort_window (void);
